package form;

import javax.swing.JOptionPane;
import config.Constanta;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.TreeMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Attachment;
import model.Attendance;
import model.Leave;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 *
 */
public class ApprovalProcess extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ApprovalProcess() {
        initComponents();
        formApprovalProcessHeaderLabelId.setVisible(false);
        formApprovalProcessHeaderLabelNik.setVisible(false);
        formApprovalProcessHeaderLabelIsUpdate.setVisible(false);
        formApprovalProcessHeaderLabelIdLeave.setVisible(false);
        formApprovalProcessHeaderLabelIsUpdate.setText(Constanta.Default.DEFAULT_VALUE);
        formApprovalProcessHeaderLabelIdLeave.setText(Constanta.Default.DEFAULT_VALUE);
        bindDataStatusLeave();
        
        formApprovalProcessMainTextFieldFullName.setEnabled(false);
        formApprovalProcessMainComboBoxType.setEnabled(false);
        formApprovalProcessMainDateChooserFrom.setEnabled(false);
        formApprovalProcessMainDateChooserTo.setEnabled(false);
        formApprovalProcessMainTextAreaReasons.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formApprovalProcessPanelHeader = new javax.swing.JPanel();
        formApprovalProcessHeaderLable = new javax.swing.JLabel();
        formApprovalProcessHeaderLabelId = new javax.swing.JLabel();
        formApprovalProcessHeaderLabelIsUpdate = new javax.swing.JLabel();
        formApprovalProcessHeaderLabelIdLeave = new javax.swing.JLabel();
        formApprovalProcessHeaderLabelNik = new javax.swing.JLabel();
        formApprovalProcessPanelFooter = new javax.swing.JPanel();
        formApprovalProcessLabelFooter2 = new javax.swing.JLabel();
        formApprovalProcessPanelMain = new javax.swing.JPanel();
        formApprovalProcessMainLabelFullNameUser = new javax.swing.JLabel();
        formApprovalProcessMainButtonBack = new javax.swing.JButton();
        formApprovalProcessMainButtonLogout = new javax.swing.JButton();
        formApprovalProcessMainPanelForm = new javax.swing.JPanel();
        formApprovalProcessMainLabelFullName = new javax.swing.JLabel();
        formApprovalProcessMainLabelFrom = new javax.swing.JLabel();
        formApprovalProcessMainLabelReasons = new javax.swing.JLabel();
        formApprovalProcessMainLabelFile = new javax.swing.JLabel();
        formApprovalProcessMainLabelTo = new javax.swing.JLabel();
        formApprovalProcessMainTextFieldFullName = new javax.swing.JTextField();
        formApprovalProcessMainComboBoxType = new javax.swing.JComboBox<>();
        formApprovalProcessMainDateChooserFrom = new com.toedter.calendar.JDateChooser();
        formApprovalProcessMainDateChooserTo = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        formApprovalProcessMainTextAreaReasons = new javax.swing.JTextArea();
        formApprovalProcessMainPanelButton = new javax.swing.JPanel();
        formApprovalProcessMainButtonSave = new javax.swing.JButton();
        formApprovalProcessMainButtonSubmit = new javax.swing.JButton();
        formApprovalProcessMainPanelFiles = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        formApprovalProcessMainTableAttachment = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frameEmployee"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        formApprovalProcessPanelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formApprovalProcessPanelHeader.setPreferredSize(new java.awt.Dimension(1280, 70));

        formApprovalProcessHeaderLable.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        formApprovalProcessHeaderLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formApprovalProcessHeaderLable.setText("Approval Process");

        formApprovalProcessHeaderLabelId.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formApprovalProcessHeaderLabelId.setText("Id");
        formApprovalProcessHeaderLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formApprovalProcessHeaderLabelIsUpdate.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formApprovalProcessHeaderLabelIsUpdate.setText("IsUpdate");
        formApprovalProcessHeaderLabelIsUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formApprovalProcessHeaderLabelIdLeave.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formApprovalProcessHeaderLabelIdLeave.setText("IdEmployee");
        formApprovalProcessHeaderLabelIdLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formApprovalProcessHeaderLabelNik.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formApprovalProcessHeaderLabelNik.setText("Nik");
        formApprovalProcessHeaderLabelNik.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout formApprovalProcessPanelHeaderLayout = new javax.swing.GroupLayout(formApprovalProcessPanelHeader);
        formApprovalProcessPanelHeader.setLayout(formApprovalProcessPanelHeaderLayout);
        formApprovalProcessPanelHeaderLayout.setHorizontalGroup(
            formApprovalProcessPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formApprovalProcessPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formApprovalProcessPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formApprovalProcessHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formApprovalProcessPanelHeaderLayout.createSequentialGroup()
                        .addComponent(formApprovalProcessHeaderLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formApprovalProcessHeaderLabelIsUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formApprovalProcessHeaderLabelIdLeave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formApprovalProcessHeaderLabelNik)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formApprovalProcessPanelHeaderLayout.setVerticalGroup(
            formApprovalProcessPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formApprovalProcessPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formApprovalProcessHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formApprovalProcessPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formApprovalProcessHeaderLabelId)
                    .addComponent(formApprovalProcessHeaderLabelIsUpdate)
                    .addComponent(formApprovalProcessHeaderLabelIdLeave)
                    .addComponent(formApprovalProcessHeaderLabelNik)))
        );

        formApprovalProcessHeaderLable.getAccessibleContext().setAccessibleDescription("");

        formApprovalProcessPanelFooter.setPreferredSize(new java.awt.Dimension(1024, 75));

        formApprovalProcessLabelFooter2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        formApprovalProcessLabelFooter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formApprovalProcessLabelFooter2.setText("Employee Content Management System CopyRight ©2021");

        javax.swing.GroupLayout formApprovalProcessPanelFooterLayout = new javax.swing.GroupLayout(formApprovalProcessPanelFooter);
        formApprovalProcessPanelFooter.setLayout(formApprovalProcessPanelFooterLayout);
        formApprovalProcessPanelFooterLayout.setHorizontalGroup(
            formApprovalProcessPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formApprovalProcessPanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formApprovalProcessLabelFooter2, javax.swing.GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE)
                .addContainerGap())
        );
        formApprovalProcessPanelFooterLayout.setVerticalGroup(
            formApprovalProcessPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formApprovalProcessPanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formApprovalProcessLabelFooter2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formApprovalProcessPanelMain.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formApprovalProcessMainLabelFullNameUser.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        formApprovalProcessMainLabelFullNameUser.setText("FullName");

        formApprovalProcessMainButtonBack.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainButtonBack.setText("Back");
        formApprovalProcessMainButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formApprovalProcessMainButtonBackActionPerformed(evt);
            }
        });
        formApprovalProcessMainButtonBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formApprovalProcessMainButtonBackKeyPressed(evt);
            }
        });

        formApprovalProcessMainButtonLogout.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainButtonLogout.setText("Logout");
        formApprovalProcessMainButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formApprovalProcessMainButtonLogoutActionPerformed(evt);
            }
        });
        formApprovalProcessMainButtonLogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formApprovalProcessMainButtonLogoutKeyPressed(evt);
            }
        });

        formApprovalProcessMainPanelForm.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        formApprovalProcessMainLabelFullName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainLabelFullName.setText("Full Name");

        formApprovalProcessMainLabelFrom.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainLabelFrom.setText("From");

        formApprovalProcessMainLabelReasons.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainLabelReasons.setText("Reasons");

        formApprovalProcessMainLabelFile.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainLabelFile.setText("Type");

        formApprovalProcessMainLabelTo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainLabelTo.setText("To");

        formApprovalProcessMainTextFieldFullName.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        formApprovalProcessMainTextFieldFullName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        formApprovalProcessMainComboBoxType.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formApprovalProcessMainDateChooserFrom.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainDateChooserFrom.setMinimumSize(new java.awt.Dimension(400, 28));
        formApprovalProcessMainDateChooserFrom.setPreferredSize(new java.awt.Dimension(400, 28));

        formApprovalProcessMainDateChooserTo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainDateChooserTo.setMinimumSize(new java.awt.Dimension(400, 28));
        formApprovalProcessMainDateChooserTo.setPreferredSize(new java.awt.Dimension(400, 28));

        formApprovalProcessMainTextAreaReasons.setColumns(20);
        formApprovalProcessMainTextAreaReasons.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainTextAreaReasons.setRows(5);
        jScrollPane1.setViewportView(formApprovalProcessMainTextAreaReasons);

        javax.swing.GroupLayout formApprovalProcessMainPanelFormLayout = new javax.swing.GroupLayout(formApprovalProcessMainPanelForm);
        formApprovalProcessMainPanelForm.setLayout(formApprovalProcessMainPanelFormLayout);
        formApprovalProcessMainPanelFormLayout.setHorizontalGroup(
            formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formApprovalProcessMainPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formApprovalProcessMainLabelFrom)
                    .addComponent(formApprovalProcessMainLabelReasons)
                    .addComponent(formApprovalProcessMainLabelFullName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(formApprovalProcessMainPanelFormLayout.createSequentialGroup()
                        .addGroup(formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formApprovalProcessMainDateChooserFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formApprovalProcessMainTextFieldFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                        .addGap(61, 61, 61)
                        .addGroup(formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formApprovalProcessMainLabelTo)
                            .addComponent(formApprovalProcessMainLabelFile))
                        .addGap(140, 140, 140)
                        .addGroup(formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formApprovalProcessMainDateChooserTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formApprovalProcessMainComboBoxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        formApprovalProcessMainPanelFormLayout.setVerticalGroup(
            formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formApprovalProcessMainPanelFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formApprovalProcessMainLabelFullName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formApprovalProcessMainComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(formApprovalProcessMainLabelFile))
                    .addComponent(formApprovalProcessMainTextFieldFullName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(formApprovalProcessMainPanelFormLayout.createSequentialGroup()
                            .addGroup(formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(formApprovalProcessMainLabelTo)
                                .addComponent(formApprovalProcessMainLabelFrom))
                            .addGap(6, 6, 6))
                        .addComponent(formApprovalProcessMainDateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formApprovalProcessMainDateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formApprovalProcessMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formApprovalProcessMainLabelReasons))
                .addGap(10, 10, 10))
        );

        formApprovalProcessMainButtonSave.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainButtonSave.setText("Approved");
        formApprovalProcessMainButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formApprovalProcessMainButtonSaveActionPerformed(evt);
            }
        });
        formApprovalProcessMainButtonSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formApprovalProcessMainButtonSaveKeyPressed(evt);
            }
        });

        formApprovalProcessMainButtonSubmit.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formApprovalProcessMainButtonSubmit.setText("Rejected");
        formApprovalProcessMainButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formApprovalProcessMainButtonSubmitActionPerformed(evt);
            }
        });
        formApprovalProcessMainButtonSubmit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formApprovalProcessMainButtonSubmitKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout formApprovalProcessMainPanelButtonLayout = new javax.swing.GroupLayout(formApprovalProcessMainPanelButton);
        formApprovalProcessMainPanelButton.setLayout(formApprovalProcessMainPanelButtonLayout);
        formApprovalProcessMainPanelButtonLayout.setHorizontalGroup(
            formApprovalProcessMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formApprovalProcessMainPanelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formApprovalProcessMainButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(formApprovalProcessMainButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337))
        );
        formApprovalProcessMainPanelButtonLayout.setVerticalGroup(
            formApprovalProcessMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formApprovalProcessMainPanelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formApprovalProcessMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formApprovalProcessMainButtonSubmit)
                    .addComponent(formApprovalProcessMainButtonSave))
                .addContainerGap())
        );

        formApprovalProcessMainPanelFiles.setBorder(javax.swing.BorderFactory.createTitledBorder("List of files"));

        formApprovalProcessMainTableAttachment.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        formApprovalProcessMainTableAttachment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Id Leave", "File Name", "File Path"
            }
        ));
        formApprovalProcessMainTableAttachment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formApprovalProcessMainTableAttachmentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(formApprovalProcessMainTableAttachment);

        javax.swing.GroupLayout formApprovalProcessMainPanelFilesLayout = new javax.swing.GroupLayout(formApprovalProcessMainPanelFiles);
        formApprovalProcessMainPanelFiles.setLayout(formApprovalProcessMainPanelFilesLayout);
        formApprovalProcessMainPanelFilesLayout.setHorizontalGroup(
            formApprovalProcessMainPanelFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formApprovalProcessMainPanelFilesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        formApprovalProcessMainPanelFilesLayout.setVerticalGroup(
            formApprovalProcessMainPanelFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formApprovalProcessMainPanelFilesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout formApprovalProcessPanelMainLayout = new javax.swing.GroupLayout(formApprovalProcessPanelMain);
        formApprovalProcessPanelMain.setLayout(formApprovalProcessPanelMainLayout);
        formApprovalProcessPanelMainLayout.setHorizontalGroup(
            formApprovalProcessPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formApprovalProcessPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formApprovalProcessPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formApprovalProcessPanelMainLayout.createSequentialGroup()
                        .addComponent(formApprovalProcessMainLabelFullNameUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 908, Short.MAX_VALUE)
                        .addComponent(formApprovalProcessMainButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formApprovalProcessMainButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formApprovalProcessMainPanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formApprovalProcessMainPanelFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(formApprovalProcessPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formApprovalProcessPanelMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formApprovalProcessMainPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        formApprovalProcessPanelMainLayout.setVerticalGroup(
            formApprovalProcessPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formApprovalProcessPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formApprovalProcessPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formApprovalProcessMainButtonLogout)
                    .addComponent(formApprovalProcessMainLabelFullNameUser)
                    .addComponent(formApprovalProcessMainButtonBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(formApprovalProcessMainPanelFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formApprovalProcessMainPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(formApprovalProcessPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formApprovalProcessPanelMainLayout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(formApprovalProcessMainPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(230, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formApprovalProcessPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 1298, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formApprovalProcessPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formApprovalProcessPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, 1278, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formApprovalProcessPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formApprovalProcessPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formApprovalProcessPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        formApprovalProcessPanelHeader.getAccessibleContext().setAccessibleName("");
        formApprovalProcessPanelHeader.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    LocalDateTime localDateTimeNow = LocalDateTime.now();
    DateTimeFormatter DATETIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
    private List<String> access_menu = new ArrayList<>();
    private String full_name;
    public List<Attachment> list_attachments = new ArrayList<>();

    public void setLabelId(String text) {
        formApprovalProcessHeaderLabelId.setText(text);
    }

    public void setLabelNik(String text) {
        formApprovalProcessHeaderLabelNik.setText(text);
    }

    public String getFullName() {
        return full_name;
    }

    public void setFullName(String text) {
        this.full_name = text;
        formApprovalProcessMainLabelFullNameUser.setText("Welcome " + text + ",");
    }

    public List<String> getAccessMenu() {
        return access_menu;
    }

    public void setAccessMenu(List<String> value) {
        this.access_menu = value;
    }

    public void setListAttachment(List<Attachment> value) {
        this.list_attachments = value;
    }
    public List<Attachment> getListAttachment() {
        return list_attachments;
    }

    public void loadDataAttachment(Leave leave) {
        List<Attachment> list = leave.getListAttachment();
        DefaultTableModel defaultTableModel = (DefaultTableModel) formApprovalProcessMainTableAttachment.getModel();
        defaultTableModel.setRowCount(0);
        Object[] rows = new Object[9];
        for (int i = 0; i < list.size(); i++) {
            TableColumnModel tableColumnModel = formApprovalProcessMainTableAttachment.getColumnModel();
            tableColumnModel.getColumn(0).setMaxWidth(0);
            tableColumnModel.getColumn(0).setMinWidth(0);
            
            tableColumnModel.getColumn(1).setMaxWidth(0);
            tableColumnModel.getColumn(1).setMinWidth(0);
            
            rows[0] = list.get(i).getId();
            rows[1] = list.get(i).getIdLeave();
            rows[2] = list.get(i).getFileName();
            rows[3] = list.get(i).getFilePath();
            
            defaultTableModel.addRow(rows);
        }
        formApprovalProcessMainTableAttachment.setAutoCreateRowSorter(true);
    }
    
    private void bindDataStatusLeave() {
        try {
            Constanta.Leave constantaLeave = new Constanta.Leave();
            HashMap<String, Integer> map = constantaLeave.getTypes();
            TreeMap<String, Integer> sortMap = new TreeMap<>(map);
            sortMap.keySet().forEach((e) -> formApprovalProcessMainComboBoxType.addItem(e));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }


    private boolean submit(String action) throws SQLException {
        boolean result = true;
        Date dateFrom = formApprovalProcessMainDateChooserFrom.getDate();
        Date dateTo = formApprovalProcessMainDateChooserTo.getDate();
        SimpleDateFormat simpleDateFormatFrom = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        SimpleDateFormat simpleDateFormatTo = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        String date_from = null;
        String date_to = null;

        if (dateFrom != null && dateTo != null) {
            date_from = simpleDateFormatFrom.format(dateFrom);
            date_to = simpleDateFormatTo.format(dateTo);
        } else {
            JOptionPane.showConfirmDialog(null, Constanta.Messages.MESSAGE_INVALID);
            return false;
        }

        Leave leave = new Leave();
        Constanta.Leave constantaLeave = new Constanta.Leave();
        HashMap<String, Integer> map = constantaLeave.getTypes();
        int type_id = Integer.parseInt(map.get(formApprovalProcessMainComboBoxType.getSelectedItem().toString()).toString());
        leave.setIdType(type_id);
        leave.setUsername(formApprovalProcessHeaderLabelNik.getText());
        leave.setRequestDate(localDateTimeNow.format(DATETIME_FORMATTER));
        leave.setDateFrom(date_from);
        leave.setDateTo(date_to);
        leave.setReasons(formApprovalProcessMainTextAreaReasons.getText());
        leave.setStatus(action);
        leave.setListAttachment(getListAttachment());

        if (formApprovalProcessHeaderLabelIsUpdate.getText().equals("1")) {
            leave.setId(Integer.parseInt(formApprovalProcessHeaderLabelIdLeave.getText()));
            result = leave.update(leave);
        } else {
            result = leave.create(leave);
        }

        return result;
    }
    
    public void clear(){
        formApprovalProcessMainTextAreaReasons.setText("");
        formApprovalProcessMainDateChooserFrom.setDate(null);
        formApprovalProcessMainDateChooserTo.setDate(null);
        setListAttachment(list_attachments = new ArrayList<>());
    }
    
    private boolean validation(){
        
        boolean result;
        
        result = !(
                formApprovalProcessMainDateChooserTo.getDate() == null
                || formApprovalProcessMainDateChooserFrom.getDate() == null
                || formApprovalProcessMainTextAreaReasons.getText().equals(""));
        
        return result;
    }
    
    public void assignValue(Leave leave) {
        try {
            SimpleDateFormat simpleDateFormatFrom = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat simpleDateFormatTo = new SimpleDateFormat("yyyy-MM-dd");
            
            Date dateFrom = simpleDateFormatFrom.parse(leave.getDateFrom());
            Date dateTo = simpleDateFormatTo.parse(leave.getDateTo());
            
            formApprovalProcessMainTextFieldFullName.setText(leave.getFullName());
            formApprovalProcessMainComboBoxType.setSelectedItem(leave.getTypeName());
            formApprovalProcessMainDateChooserFrom.setDate(dateFrom);
            formApprovalProcessMainDateChooserTo.setDate(dateTo);
            formApprovalProcessMainTextAreaReasons.setText(leave.getReasons());
            formApprovalProcessHeaderLabelIsUpdate.setText("1");
            formApprovalProcessHeaderLabelIdLeave.setText(leave.getId().toString());
            loadDataAttachment(leave);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }
    
    private void formApprovalProcessMainButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formApprovalProcessMainButtonBackActionPerformed
        // TODO add your handling code here:        
        try {
            ApprovalDetail approvalDetail = new ApprovalDetail();
            approvalDetail.show(true);
            approvalDetail.setLabelId(formApprovalProcessHeaderLabelId.getText());
            approvalDetail.setLabelNik(formApprovalProcessHeaderLabelNik.getText());
            approvalDetail.setFullName(getFullName());
            approvalDetail.setAccessMenu(getAccessMenu());
            approvalDetail.loadDataApproval();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formApprovalProcessMainButtonBackActionPerformed

    private void formApprovalProcessMainButtonBackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formApprovalProcessMainButtonBackKeyPressed
        // TODO add your handling code here:        
        try {
            ApprovalDetail approvalDetail = new ApprovalDetail();
            approvalDetail.show(true);
            approvalDetail.setLabelId(formApprovalProcessHeaderLabelId.getText());
            approvalDetail.setLabelNik(formApprovalProcessHeaderLabelNik.getText());
            approvalDetail.setFullName(getFullName());
            approvalDetail.setAccessMenu(getAccessMenu());
            approvalDetail.loadDataApproval();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formApprovalProcessMainButtonBackKeyPressed

    private void formApprovalProcessMainButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formApprovalProcessMainButtonLogoutActionPerformed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formApprovalProcessMainButtonLogoutActionPerformed

    private void formApprovalProcessMainButtonLogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formApprovalProcessMainButtonLogoutKeyPressed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formApprovalProcessMainButtonLogoutKeyPressed

    private void formApprovalProcessMainButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formApprovalProcessMainButtonSaveActionPerformed
        // TODO add your handling code here:
        try {
            if (validation()) {
                if (submit(Constanta.Leave.DRAF)) {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
                    clear();
                    Dashboard dashboard = new Dashboard();
                    dashboard.show();
                    dashboard.setLabelId(formApprovalProcessHeaderLabelId.getText());
                    dashboard.setLabelNik(formApprovalProcessHeaderLabelNik.getText());
                    dashboard.setFullName(getFullName());
                    dashboard.setAccessMenu(getAccessMenu());
                    dashboard.loadDataAttendance();
                    dashboard.loadDataLeave();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formApprovalProcessMainButtonSaveActionPerformed

    private void formApprovalProcessMainButtonSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formApprovalProcessMainButtonSaveKeyPressed
        // TODO add your handling code here:
        try {
            if (validation()) {
                if (submit(Constanta.Leave.DRAF)) {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
                    clear();
                    Dashboard dashboard = new Dashboard();
                    dashboard.show();
                    dashboard.setLabelId(formApprovalProcessHeaderLabelId.getText());
                    dashboard.setLabelNik(formApprovalProcessHeaderLabelNik.getText());
                    dashboard.setFullName(getFullName());
                    dashboard.setAccessMenu(getAccessMenu());
                    dashboard.loadDataAttendance();
                    dashboard.loadDataLeave();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formApprovalProcessMainButtonSaveKeyPressed

    private void formApprovalProcessMainButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formApprovalProcessMainButtonSubmitActionPerformed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_SUBMIT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (action == JOptionPane.YES_OPTION) {
                if (validation()) {
                    if (submit(Constanta.Leave.SUBMIT)) {
                        JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
                    } else {
                        JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
                    }
                }
            }
            clear();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formApprovalProcessMainButtonSubmitActionPerformed

    private void formApprovalProcessMainButtonSubmitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formApprovalProcessMainButtonSubmitKeyPressed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_SUBMIT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (action == JOptionPane.YES_OPTION) {
                if (validation()) {
                    if (submit(Constanta.Leave.SUBMIT)) {
                        JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
                    } else {
                        JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
                    }
                }
            }
            clear();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formApprovalProcessMainButtonSubmitKeyPressed

    private void formApprovalProcessMainTableAttachmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formApprovalProcessMainTableAttachmentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formApprovalProcessMainTableAttachmentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApprovalProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApprovalProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApprovalProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApprovalProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApprovalProcess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel formApprovalProcessHeaderLabelId;
    public javax.swing.JLabel formApprovalProcessHeaderLabelIdLeave;
    public javax.swing.JLabel formApprovalProcessHeaderLabelIsUpdate;
    public javax.swing.JLabel formApprovalProcessHeaderLabelNik;
    private javax.swing.JLabel formApprovalProcessHeaderLable;
    private javax.swing.JLabel formApprovalProcessLabelFooter2;
    private javax.swing.JButton formApprovalProcessMainButtonBack;
    private javax.swing.JButton formApprovalProcessMainButtonLogout;
    private javax.swing.JButton formApprovalProcessMainButtonSave;
    private javax.swing.JButton formApprovalProcessMainButtonSubmit;
    private javax.swing.JComboBox<String> formApprovalProcessMainComboBoxType;
    private com.toedter.calendar.JDateChooser formApprovalProcessMainDateChooserFrom;
    private com.toedter.calendar.JDateChooser formApprovalProcessMainDateChooserTo;
    private javax.swing.JLabel formApprovalProcessMainLabelFile;
    private javax.swing.JLabel formApprovalProcessMainLabelFrom;
    private javax.swing.JLabel formApprovalProcessMainLabelFullName;
    private javax.swing.JLabel formApprovalProcessMainLabelFullNameUser;
    private javax.swing.JLabel formApprovalProcessMainLabelReasons;
    private javax.swing.JLabel formApprovalProcessMainLabelTo;
    private javax.swing.JPanel formApprovalProcessMainPanelButton;
    private javax.swing.JPanel formApprovalProcessMainPanelFiles;
    private javax.swing.JPanel formApprovalProcessMainPanelForm;
    private javax.swing.JTable formApprovalProcessMainTableAttachment;
    private javax.swing.JTextArea formApprovalProcessMainTextAreaReasons;
    private javax.swing.JTextField formApprovalProcessMainTextFieldFullName;
    private javax.swing.JPanel formApprovalProcessPanelFooter;
    private javax.swing.JPanel formApprovalProcessPanelHeader;
    private javax.swing.JPanel formApprovalProcessPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
