package form;

import javax.swing.JOptionPane;
import config.Constanta;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Attendance;
import model.Leave;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author bason
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Dashboard() {
        initComponents();
        formDashboardHeaderLabelId.setVisible(false);
        formDashboardHeaderLabelNik.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formDashboardPanelHeader = new javax.swing.JPanel();
        formDashboardHeaderLable = new javax.swing.JLabel();
        formDashboardHeaderLabelId = new javax.swing.JLabel();
        formDashboardHeaderLabelNik = new javax.swing.JLabel();
        formDashboardPanelFooter = new javax.swing.JPanel();
        formDashboardLabelFooter2 = new javax.swing.JLabel();
        formDashboardPanelMain = new javax.swing.JPanel();
        formDashboardMainLabelFullName = new javax.swing.JLabel();
        formDashboardMainButtonLogout = new javax.swing.JButton();
        formDashboardMainButtonEmployee = new javax.swing.JButton();
        formDashboardMainButtonReport = new javax.swing.JButton();
        formDashboardMainButtonApproval = new javax.swing.JButton();
        formDashboardMainAttendancePanelTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        formDashboardMainAttendanceTable = new javax.swing.JTable();
        formDashboardMainAttendanceCheckin = new javax.swing.JButton();
        formDashboardMainAttendanceCheckout = new javax.swing.JButton();
        formDashboardMainAttendanceViewMore = new javax.swing.JButton();
        formDashboardMainAttendancePanel = new javax.swing.JPanel();
        formDashboardMainAttendanceButtonSearch = new javax.swing.JButton();
        formDashboardMainAttendanceLebelFrom = new javax.swing.JLabel();
        formDashboardMainAttendanceLebelTo = new javax.swing.JLabel();
        formDashboardMainAttendanceJDateChooseFrom = new com.toedter.calendar.JDateChooser();
        formDashboardMainAttendanceJDateChooseTo = new com.toedter.calendar.JDateChooser();
        formDashboardMainLeavePanelTable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        formDashboardMainLeaveTable = new javax.swing.JTable();
        formDashboardMainLeaveRequest = new javax.swing.JButton();
        formDashboardMainLeaveView = new javax.swing.JButton();
        formDashboardMainLeavePanel = new javax.swing.JPanel();
        formDashboardMainLeaveButtonSearch = new javax.swing.JButton();
        formDashboardMainLeaveLebelFrom = new javax.swing.JLabel();
        formDashboardMainLeaveLebelTo = new javax.swing.JLabel();
        formDashboardMainLeaveJDateChooseFrom = new com.toedter.calendar.JDateChooser();
        formDashboardMainLeaveJDateChooseTo = new com.toedter.calendar.JDateChooser();
        formDashboardMainPayslipPanelTable = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        formDashboardMainPayslipTable = new javax.swing.JTable();
        formDashboardMainPayslipView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frameEmployee"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        formDashboardPanelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formDashboardPanelHeader.setPreferredSize(new java.awt.Dimension(1024, 100));

        formDashboardHeaderLable.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        formDashboardHeaderLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formDashboardHeaderLable.setText("Dashboard");

        formDashboardHeaderLabelId.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formDashboardHeaderLabelId.setText("Id");
        formDashboardHeaderLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formDashboardHeaderLabelNik.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formDashboardHeaderLabelNik.setText("Nik");
        formDashboardHeaderLabelNik.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout formDashboardPanelHeaderLayout = new javax.swing.GroupLayout(formDashboardPanelHeader);
        formDashboardPanelHeader.setLayout(formDashboardPanelHeaderLayout);
        formDashboardPanelHeaderLayout.setHorizontalGroup(
            formDashboardPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formDashboardPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formDashboardHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
                    .addGroup(formDashboardPanelHeaderLayout.createSequentialGroup()
                        .addComponent(formDashboardHeaderLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formDashboardHeaderLabelNik)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formDashboardPanelHeaderLayout.setVerticalGroup(
            formDashboardPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formDashboardHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formDashboardPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDashboardHeaderLabelId)
                    .addComponent(formDashboardHeaderLabelNik)))
        );

        formDashboardHeaderLable.getAccessibleContext().setAccessibleDescription("");

        formDashboardPanelFooter.setPreferredSize(new java.awt.Dimension(1024, 75));

        formDashboardLabelFooter2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        formDashboardLabelFooter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formDashboardLabelFooter2.setText("Employee Content Management System CopyRight ©2021");

        javax.swing.GroupLayout formDashboardPanelFooterLayout = new javax.swing.GroupLayout(formDashboardPanelFooter);
        formDashboardPanelFooter.setLayout(formDashboardPanelFooterLayout);
        formDashboardPanelFooterLayout.setHorizontalGroup(
            formDashboardPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardPanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formDashboardLabelFooter2, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
                .addContainerGap())
        );
        formDashboardPanelFooterLayout.setVerticalGroup(
            formDashboardPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardPanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formDashboardLabelFooter2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formDashboardMainLabelFullName.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        formDashboardMainLabelFullName.setText("FullName");

        formDashboardMainButtonLogout.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainButtonLogout.setText("Logout");
        formDashboardMainButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainButtonLogoutActionPerformed(evt);
            }
        });
        formDashboardMainButtonLogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainButtonLogoutKeyPressed(evt);
            }
        });

        formDashboardMainButtonEmployee.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainButtonEmployee.setText("Employee");
        formDashboardMainButtonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainButtonEmployeeActionPerformed(evt);
            }
        });
        formDashboardMainButtonEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainButtonEmployeeKeyPressed(evt);
            }
        });

        formDashboardMainButtonReport.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainButtonReport.setText("Report");
        formDashboardMainButtonReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainButtonReportActionPerformed(evt);
            }
        });
        formDashboardMainButtonReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainButtonReportKeyPressed(evt);
            }
        });

        formDashboardMainButtonApproval.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainButtonApproval.setText("Approval");
        formDashboardMainButtonApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainButtonApprovalActionPerformed(evt);
            }
        });
        formDashboardMainButtonApproval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainButtonApprovalKeyPressed(evt);
            }
        });

        formDashboardMainAttendancePanelTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Attendance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 11))); // NOI18N

        formDashboardMainAttendanceTable.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        formDashboardMainAttendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nik", "Full Name", "Check In", "Check Out", "Location", "Duration", "Status", "Information"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        formDashboardMainAttendanceTable.setColumnSelectionAllowed(true);
        formDashboardMainAttendanceTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formDashboardMainAttendanceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formDashboardMainAttendanceTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(formDashboardMainAttendanceTable);
        formDashboardMainAttendanceTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (formDashboardMainAttendanceTable.getColumnModel().getColumnCount() > 0) {
            formDashboardMainAttendanceTable.getColumnModel().getColumn(0).setHeaderValue("Id");
            formDashboardMainAttendanceTable.getColumnModel().getColumn(1).setHeaderValue("Nik");
            formDashboardMainAttendanceTable.getColumnModel().getColumn(2).setHeaderValue("Full Name");
            formDashboardMainAttendanceTable.getColumnModel().getColumn(3).setHeaderValue("Check In");
            formDashboardMainAttendanceTable.getColumnModel().getColumn(4).setHeaderValue("Check Out");
            formDashboardMainAttendanceTable.getColumnModel().getColumn(5).setHeaderValue("Location");
            formDashboardMainAttendanceTable.getColumnModel().getColumn(6).setHeaderValue("Duration");
            formDashboardMainAttendanceTable.getColumnModel().getColumn(7).setHeaderValue("Status");
            formDashboardMainAttendanceTable.getColumnModel().getColumn(8).setHeaderValue("Information");
        }

        formDashboardMainAttendanceCheckin.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainAttendanceCheckin.setText("Check In");
        formDashboardMainAttendanceCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainAttendanceCheckinActionPerformed(evt);
            }
        });
        formDashboardMainAttendanceCheckin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainAttendanceCheckinKeyPressed(evt);
            }
        });

        formDashboardMainAttendanceCheckout.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainAttendanceCheckout.setText("Check Out");
        formDashboardMainAttendanceCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainAttendanceCheckoutActionPerformed(evt);
            }
        });
        formDashboardMainAttendanceCheckout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainAttendanceCheckoutKeyPressed(evt);
            }
        });

        formDashboardMainAttendanceViewMore.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainAttendanceViewMore.setText("View more");

        formDashboardMainAttendanceButtonSearch.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainAttendanceButtonSearch.setText("Search");
        formDashboardMainAttendanceButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainAttendanceButtonSearchActionPerformed(evt);
            }
        });
        formDashboardMainAttendanceButtonSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainAttendanceButtonSearchKeyPressed(evt);
            }
        });

        formDashboardMainAttendanceLebelFrom.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainAttendanceLebelFrom.setText("From");

        formDashboardMainAttendanceLebelTo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainAttendanceLebelTo.setText("To");

        formDashboardMainAttendanceJDateChooseFrom.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formDashboardMainAttendanceJDateChooseTo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout formDashboardMainAttendancePanelLayout = new javax.swing.GroupLayout(formDashboardMainAttendancePanel);
        formDashboardMainAttendancePanel.setLayout(formDashboardMainAttendancePanelLayout);
        formDashboardMainAttendancePanelLayout.setHorizontalGroup(
            formDashboardMainAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formDashboardMainAttendancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formDashboardMainAttendanceLebelFrom)
                .addGap(18, 18, 18)
                .addComponent(formDashboardMainAttendanceJDateChooseFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formDashboardMainAttendanceLebelTo)
                .addGap(18, 18, 18)
                .addComponent(formDashboardMainAttendanceJDateChooseTo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formDashboardMainAttendanceButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );
        formDashboardMainAttendancePanelLayout.setVerticalGroup(
            formDashboardMainAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formDashboardMainAttendancePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formDashboardMainAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formDashboardMainAttendanceButtonSearch)
                    .addComponent(formDashboardMainAttendanceJDateChooseTo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formDashboardMainAttendancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formDashboardMainAttendanceLebelFrom)
                        .addComponent(formDashboardMainAttendanceLebelTo))
                    .addComponent(formDashboardMainAttendanceJDateChooseFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout formDashboardMainAttendancePanelTableLayout = new javax.swing.GroupLayout(formDashboardMainAttendancePanelTable);
        formDashboardMainAttendancePanelTable.setLayout(formDashboardMainAttendancePanelTableLayout);
        formDashboardMainAttendancePanelTableLayout.setHorizontalGroup(
            formDashboardMainAttendancePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardMainAttendancePanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formDashboardMainAttendancePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(formDashboardMainAttendancePanelTableLayout.createSequentialGroup()
                        .addComponent(formDashboardMainAttendanceCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formDashboardMainAttendanceCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(formDashboardMainAttendanceViewMore, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formDashboardMainAttendancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formDashboardMainAttendancePanelTableLayout.setVerticalGroup(
            formDashboardMainAttendancePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardMainAttendancePanelTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formDashboardMainAttendancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formDashboardMainAttendancePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDashboardMainAttendanceCheckin)
                    .addComponent(formDashboardMainAttendanceViewMore)
                    .addComponent(formDashboardMainAttendanceCheckout))
                .addContainerGap())
        );

        formDashboardMainLeavePanelTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Leave Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 11))); // NOI18N

        formDashboardMainLeaveTable.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        formDashboardMainLeaveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nik", "Full Name", "Request Date", "Date From", "Date To", "Reasons", "Attachment", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        formDashboardMainLeaveTable.setColumnSelectionAllowed(true);
        formDashboardMainLeaveTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formDashboardMainLeaveTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(formDashboardMainLeaveTable);
        formDashboardMainLeaveTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        formDashboardMainLeaveRequest.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainLeaveRequest.setText("Request Leave");
        formDashboardMainLeaveRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainLeaveRequestActionPerformed(evt);
            }
        });

        formDashboardMainLeaveView.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainLeaveView.setText("View more");

        formDashboardMainLeaveButtonSearch.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainLeaveButtonSearch.setText("Search");
        formDashboardMainLeaveButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainLeaveButtonSearchActionPerformed(evt);
            }
        });
        formDashboardMainLeaveButtonSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainLeaveButtonSearchKeyPressed(evt);
            }
        });

        formDashboardMainLeaveLebelFrom.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainLeaveLebelFrom.setText("From");

        formDashboardMainLeaveLebelTo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainLeaveLebelTo.setText("To");

        formDashboardMainLeaveJDateChooseFrom.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formDashboardMainLeaveJDateChooseTo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout formDashboardMainLeavePanelLayout = new javax.swing.GroupLayout(formDashboardMainLeavePanel);
        formDashboardMainLeavePanel.setLayout(formDashboardMainLeavePanelLayout);
        formDashboardMainLeavePanelLayout.setHorizontalGroup(
            formDashboardMainLeavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formDashboardMainLeavePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formDashboardMainLeaveLebelFrom)
                .addGap(18, 18, 18)
                .addComponent(formDashboardMainLeaveJDateChooseFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formDashboardMainLeaveLebelTo)
                .addGap(18, 18, 18)
                .addComponent(formDashboardMainLeaveJDateChooseTo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formDashboardMainLeaveButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formDashboardMainLeavePanelLayout.setVerticalGroup(
            formDashboardMainLeavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formDashboardMainLeavePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formDashboardMainLeavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formDashboardMainLeaveButtonSearch)
                    .addComponent(formDashboardMainLeaveJDateChooseTo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formDashboardMainLeavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formDashboardMainLeaveLebelFrom)
                        .addComponent(formDashboardMainLeaveLebelTo))
                    .addComponent(formDashboardMainLeaveJDateChooseFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout formDashboardMainLeavePanelTableLayout = new javax.swing.GroupLayout(formDashboardMainLeavePanelTable);
        formDashboardMainLeavePanelTable.setLayout(formDashboardMainLeavePanelTableLayout);
        formDashboardMainLeavePanelTableLayout.setHorizontalGroup(
            formDashboardMainLeavePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardMainLeavePanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formDashboardMainLeavePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(formDashboardMainLeavePanelTableLayout.createSequentialGroup()
                        .addComponent(formDashboardMainLeaveRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formDashboardMainLeaveView, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formDashboardMainLeavePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formDashboardMainLeavePanelTableLayout.setVerticalGroup(
            formDashboardMainLeavePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardMainLeavePanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formDashboardMainLeavePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formDashboardMainLeavePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDashboardMainLeaveRequest)
                    .addComponent(formDashboardMainLeaveView))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formDashboardMainPayslipPanelTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payslip", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 11))); // NOI18N

        formDashboardMainPayslipTable.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        formDashboardMainPayslipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nik", "First Name", "Last Name", "Position", "Address", "Salary", "Days Off", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        formDashboardMainPayslipTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formDashboardMainPayslipTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(formDashboardMainPayslipTable);
        formDashboardMainPayslipTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        formDashboardMainPayslipView.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainPayslipView.setText("View more");

        javax.swing.GroupLayout formDashboardMainPayslipPanelTableLayout = new javax.swing.GroupLayout(formDashboardMainPayslipPanelTable);
        formDashboardMainPayslipPanelTable.setLayout(formDashboardMainPayslipPanelTableLayout);
        formDashboardMainPayslipPanelTableLayout.setHorizontalGroup(
            formDashboardMainPayslipPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardMainPayslipPanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formDashboardMainPayslipPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(formDashboardMainPayslipView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formDashboardMainPayslipPanelTableLayout.setVerticalGroup(
            formDashboardMainPayslipPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardMainPayslipPanelTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formDashboardMainPayslipView))
        );

        javax.swing.GroupLayout formDashboardPanelMainLayout = new javax.swing.GroupLayout(formDashboardPanelMain);
        formDashboardPanelMain.setLayout(formDashboardPanelMainLayout);
        formDashboardPanelMainLayout.setHorizontalGroup(
            formDashboardPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardPanelMainLayout.createSequentialGroup()
                .addGroup(formDashboardPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formDashboardPanelMainLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(formDashboardMainLabelFullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formDashboardMainButtonApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formDashboardMainButtonReport, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formDashboardMainButtonEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formDashboardMainButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formDashboardPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(formDashboardPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formDashboardMainPayslipPanelTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formDashboardMainLeavePanelTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formDashboardMainAttendancePanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        formDashboardPanelMainLayout.setVerticalGroup(
            formDashboardPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formDashboardPanelMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(formDashboardPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDashboardMainButtonLogout)
                    .addComponent(formDashboardMainLabelFullName)
                    .addComponent(formDashboardMainButtonEmployee)
                    .addComponent(formDashboardMainButtonReport)
                    .addComponent(formDashboardMainButtonApproval))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formDashboardMainAttendancePanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formDashboardMainLeavePanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formDashboardMainPayslipPanelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formDashboardPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formDashboardPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formDashboardPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formDashboardPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formDashboardPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formDashboardPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        formDashboardPanelHeader.getAccessibleContext().setAccessibleName("");
        formDashboardPanelHeader.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    LocalDateTime localDateTimeNow = LocalDateTime.now();
    DateTimeFormatter DATETIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private List<String> access_menu = new ArrayList<>();
    private String full_name;

    public void setLabelId(String text) {
        formDashboardHeaderLabelId.setText(text);
    }

    public void setLabelNik(String text) {
        formDashboardHeaderLabelNik.setText(text);
    }
    
    public String getFullName(){
        return full_name;
    }
    public void setFullName(String text) {
        this.full_name = text;
        formDashboardMainLabelFullName.setText("Welcome " + text + ",");
    }

    public List<String> getAccessMenu() {
        return access_menu;
    }
    public void setAccessMenu(List<String> value) {
        this.access_menu = value;
    }
    
    public void loadDataAttendance(){
        try {
            List<Attendance> listAttendance;
            if (formDashboardHeaderLabelNik.getText().equals("hrd") 
                    || formDashboardHeaderLabelNik.getText().equals("admin")) {
                listAttendance = Attendance.listParams()
                        .withUsername("")
                        .withDateFrom(null)
                        .withDateTo(null)
                        .build();
            } else {
                listAttendance = Attendance.listParams()
                        .withUsername(formDashboardHeaderLabelNik.getText())
                        .withDateFrom(null)
                        .withDateTo(null)
                        .build();
            }
            
            DefaultTableModel defaultTableModel = (DefaultTableModel) formDashboardMainAttendanceTable.getModel();
            defaultTableModel.setRowCount(0);
            Object[] rows = new Object[9];
            for(int i = 0; i < listAttendance.size(); i++){
                TableColumnModel tableColumnModel = formDashboardMainAttendanceTable.getColumnModel();
                tableColumnModel.getColumn(0).setMaxWidth(0);
                tableColumnModel.getColumn(0).setMinWidth(0);
                
                rows[0] = listAttendance.get(i).getId();
                rows[1] = listAttendance.get(i).getUsername();
                rows[2] = listAttendance.get(i).getFullName();
                rows[3] = listAttendance.get(i).getCheckIn();
                rows[4] = listAttendance.get(i).getCheckOut();
                rows[5] = listAttendance.get(i).getLocation();
                rows[6] = String.format("%.0f", listAttendance.get(i).getDuration());
                rows[7] = listAttendance.get(i).getStatus();
                rows[8] = listAttendance.get(i).getInformation();

                defaultTableModel.addRow(rows);
            }
            formDashboardMainAttendanceTable.setAutoCreateRowSorter(true);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }
    
    public void searchDataAttendance(){
        try {
            Date dateFrom = formDashboardMainAttendanceJDateChooseFrom.getDate();
            Date dateTo = formDashboardMainAttendanceJDateChooseTo.getDate();
            SimpleDateFormat simpleDateFormatFrom = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            SimpleDateFormat simpleDateFormatTo = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String date_from = simpleDateFormatFrom.format(dateFrom);
            String date_to = simpleDateFormatTo.format(dateTo);
            
            List<Attendance> listAttendance;
            if (formDashboardHeaderLabelNik.getText().equals("hrd") 
                    || formDashboardHeaderLabelNik.getText().equals("admin")) {
                listAttendance = Attendance.listParams()
                        .withUsername("")
                        .withDateFrom(date_from)
                        .withDateTo(date_to)
                        .build();
            } else {
                listAttendance = Attendance.listParams()
                        .withUsername(formDashboardHeaderLabelNik.getText())
                        .withDateFrom(date_from)
                        .withDateTo(date_to)
                        .build();
            }
            
            DefaultTableModel defaultTableModel = (DefaultTableModel) formDashboardMainAttendanceTable.getModel();
            defaultTableModel.setRowCount(0);
            Object[] rows = new Object[9];
            for(int i = 0; i < listAttendance.size(); i++){
                TableColumnModel tableColumnModel = formDashboardMainAttendanceTable.getColumnModel();
                tableColumnModel.getColumn(0).setMaxWidth(0);
                tableColumnModel.getColumn(0).setMinWidth(0);
                
                rows[0] = listAttendance.get(i).getId();
                rows[1] = listAttendance.get(i).getUsername();
                rows[2] = listAttendance.get(i).getFullName();
                rows[3] = listAttendance.get(i).getCheckIn();
                rows[4] = listAttendance.get(i).getCheckOut();
                rows[5] = listAttendance.get(i).getLocation();
                rows[6] = String.format("%.0f", listAttendance.get(i).getDuration());
                rows[7] = listAttendance.get(i).getStatus();
                rows[8] = listAttendance.get(i).getInformation();

                defaultTableModel.addRow(rows);
            }
            formDashboardMainAttendanceTable.setAutoCreateRowSorter(true);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }
    
    public void loadDataLeave(){
        try {
            List<Leave> listLeave;
            if (formDashboardHeaderLabelNik.getText().equals("hrd") 
                    || formDashboardHeaderLabelNik.getText().equals("admin")) {
                listLeave = Leave.listParams()
                        .withUsername("")
                        .withDateFrom(null)
                        .withDateTo(null)
                        .build();
            } else {
                listLeave = Leave.listParams()
                        .withUsername(formDashboardHeaderLabelNik.getText())
                        .withDateFrom(null)
                        .withDateTo(null)
                        .build();
            }
            
            DefaultTableModel defaultTableModel = (DefaultTableModel) formDashboardMainLeaveTable.getModel();
            defaultTableModel.setRowCount(0);
            Object[] rows = new Object[9];
            for(int i = 0; i < listLeave.size(); i++){
                TableColumnModel tableColumnModel = formDashboardMainLeaveTable.getColumnModel();
                tableColumnModel.getColumn(0).setMaxWidth(0);
                tableColumnModel.getColumn(0).setMinWidth(0);
                
                rows[0] = listLeave.get(i).getId();
                rows[1] = listLeave.get(i).getUsername();
                rows[2] = listLeave.get(i).getFullName();
                rows[3] = listLeave.get(i).getRequestDate();
                rows[4] = listLeave.get(i).getDateFrom();
                rows[5] = listLeave.get(i).getDateTo();
                rows[6] = listLeave.get(i).getReasons();
                rows[7] = listLeave.get(i).getListAttachment().get(0).getFileName();
                rows[8] = listLeave.get(i).getStatus();

                defaultTableModel.addRow(rows);
            }
            formDashboardMainLeaveTable.setAutoCreateRowSorter(true);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }
    
    public void searchDataLeave(){
        try {
            Date dateFrom = formDashboardMainLeaveJDateChooseFrom.getDate();
            Date dateTo = formDashboardMainLeaveJDateChooseTo.getDate();
            SimpleDateFormat simpleDateFormatFrom = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            SimpleDateFormat simpleDateFormatTo = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String date_from = simpleDateFormatFrom.format(dateFrom);
            String date_to = simpleDateFormatTo.format(dateTo);
            
            List<Leave> listLeave;
            if (formDashboardHeaderLabelNik.getText().equals("hrd") 
                    || formDashboardHeaderLabelNik.getText().equals("admin")) {
                listLeave = Leave.listParams()
                        .withUsername("")
                        .withDateFrom(null)
                        .withDateTo(null)
                        .build();
            } else {
                listLeave = Leave.listParams()
                        .withUsername(formDashboardHeaderLabelNik.getText())
                        .withDateFrom(date_from)
                        .withDateTo(date_to)
                        .build();
            }
            
            DefaultTableModel defaultTableModel = (DefaultTableModel) formDashboardMainLeaveTable.getModel();
            defaultTableModel.setRowCount(0);
            Object[] rows = new Object[9];
            for(int i = 0; i < listLeave.size(); i++){
                TableColumnModel tableColumnModel = formDashboardMainLeaveTable.getColumnModel();
                tableColumnModel.getColumn(0).setMaxWidth(0);
                tableColumnModel.getColumn(0).setMinWidth(0);
                
                rows[0] = listLeave.get(i).getId();
                rows[1] = listLeave.get(i).getUsername();
                rows[2] = listLeave.get(i).getFullName();
                rows[3] = listLeave.get(i).getRequestDate();
                rows[4] = listLeave.get(i).getDateFrom();
                rows[5] = listLeave.get(i).getDateTo();
                rows[6] = listLeave.get(i).getReasons();
                rows[7] = listLeave.get(i).getListAttachment().get(0).getFileName();
                rows[8] = listLeave.get(i).getStatus();

                defaultTableModel.addRow(rows);
            }
            formDashboardMainLeaveTable.setAutoCreateRowSorter(true);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }
    
    private boolean checkIn() throws SQLException{
        boolean result;
        
        Attendance attendance = new Attendance();
        attendance.setUsername(formDashboardHeaderLabelNik.getText());
        attendance.setCheckIn(localDateTimeNow.format(DATETIME_FORMATTER));
        attendance.setLocation(Constanta.Default.DEFAULT_LOCATION);
        attendance.setStatus(Constanta.Default.DEFAULT_CHECKIN_STATUS);
        attendance.setInformation(String.format(Constanta.Default.DEFAULT_CHECKIN_INFORMATION, 
                getFullName(), 
                localDateTimeNow.format(DATETIME_FORMATTER),
                Constanta.Default.DEFAULT_LOCATION));
        result = attendance.checkIn(attendance);
        
        return result;
    }
    
    private boolean checkOut(Attendance attendance) throws SQLException{
        boolean result;
        
        attendance.setId(attendance.getId());
        attendance.setInformation(String.format(Constanta.Default.DEFAULT_CHECKOUT_INFORMATION,
                getFullName(), 
                localDateTimeNow.format(DATETIME_FORMATTER),
                Constanta.Default.DEFAULT_LOCATION,
                "0"));
        result = attendance.checkOut(attendance);
        
        return result;
    }
    
    private void formDashboardMainAttendanceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formDashboardMainAttendanceTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formDashboardMainAttendanceTableMouseClicked

    private void formDashboardMainButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainButtonLogoutActionPerformed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonLogoutActionPerformed

    private void formDashboardMainButtonLogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainButtonLogoutKeyPressed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonLogoutKeyPressed

    private void formDashboardMainButtonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainButtonEmployeeActionPerformed
        // TODO add your handling code here:
        try {
            EmployeeManagement employeeManagement = new EmployeeManagement();
            employeeManagement.show(true);
            employeeManagement.setLabelId(formDashboardHeaderLabelId.getText());
            employeeManagement.setLabelNik(formDashboardHeaderLabelNik.getText());
            employeeManagement.setFullName(getFullName());
            employeeManagement.setAccessMenu(getAccessMenu());
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonEmployeeActionPerformed

    private void formDashboardMainButtonEmployeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainButtonEmployeeKeyPressed
        // TODO add your handling code here:
        try {
            EmployeeManagement employeeManagement = new EmployeeManagement();
            employeeManagement.show(true);
            employeeManagement.setLabelId(formDashboardHeaderLabelId.getText());
            employeeManagement.setLabelNik(formDashboardHeaderLabelNik.getText());
            employeeManagement.setFullName(getFullName());
            employeeManagement.setAccessMenu(getAccessMenu());
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonEmployeeKeyPressed

    private void formDashboardMainButtonReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainButtonReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formDashboardMainButtonReportActionPerformed

    private void formDashboardMainButtonReportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainButtonReportKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formDashboardMainButtonReportKeyPressed

    private void formDashboardMainButtonApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainButtonApprovalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formDashboardMainButtonApprovalActionPerformed

    private void formDashboardMainButtonApprovalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainButtonApprovalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formDashboardMainButtonApprovalKeyPressed

    private void formDashboardMainLeaveTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formDashboardMainLeaveTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formDashboardMainLeaveTableMouseClicked

    private void formDashboardMainLeaveRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainLeaveRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formDashboardMainLeaveRequestActionPerformed

    private void formDashboardMainPayslipTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formDashboardMainPayslipTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formDashboardMainPayslipTableMouseClicked

    private void formDashboardMainAttendanceCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainAttendanceCheckinActionPerformed
        // TODO add your handling code here:
        try {
            Attendance attendance = new Attendance();
            Attendance result = attendance.getCurrentCheckIn(formDashboardHeaderLabelNik.getText());
            if(result.getId() == null){
                if (checkIn()) {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
                } else {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
                }
            } else {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ALREADY_CHECKIN);
            }
            loadDataAttendance();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainAttendanceCheckinActionPerformed

    private void formDashboardMainAttendanceCheckinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainAttendanceCheckinKeyPressed
        // TODO add your handling code here:
        try {
            Attendance attendance = new Attendance();
            Attendance result = attendance.getCurrentCheckIn(formDashboardHeaderLabelNik.getText());
            if(result.getId() == null){
                if (checkIn()) {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
                } else {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
                }
            } else {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ALREADY_CHECKIN);
            }
            loadDataAttendance();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainAttendanceCheckinKeyPressed

    private void formDashboardMainAttendanceCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainAttendanceCheckoutActionPerformed
        // TODO add your handling code here:
        try {
            Attendance attendance = new Attendance();
            Attendance result = attendance.getCurrentCheckIn(formDashboardHeaderLabelNik.getText());
            if(result.getId() != null){
                if (checkOut(result)) {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
                } else {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
                }
            } else {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ALREADY_CHECKOUT);
            }
            loadDataAttendance();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainAttendanceCheckoutActionPerformed

    private void formDashboardMainAttendanceCheckoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainAttendanceCheckoutKeyPressed
        // TODO add your handling code here:
        try {
            Attendance attendance = new Attendance();
            Attendance result = attendance.getCurrentCheckIn(formDashboardHeaderLabelNik.getText());
            if(result.getId() != null){
                if (checkOut(result)) {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
                } else {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
                }
            } else {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ALREADY_CHECKOUT);
            }
            loadDataAttendance();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainAttendanceCheckoutKeyPressed

    private void formDashboardMainAttendanceButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainAttendanceButtonSearchActionPerformed
        // TODO add your handling code here:
        try {
            searchDataAttendance();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainAttendanceButtonSearchActionPerformed

    private void formDashboardMainAttendanceButtonSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainAttendanceButtonSearchKeyPressed
        // TODO add your handling code here:
        try {
            searchDataAttendance();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainAttendanceButtonSearchKeyPressed

    private void formDashboardMainLeaveButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainLeaveButtonSearchActionPerformed
        // TODO add your handling code here:
        try {
            searchDataLeave();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainLeaveButtonSearchActionPerformed

    private void formDashboardMainLeaveButtonSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainLeaveButtonSearchKeyPressed
        // TODO add your handling code here:
        try {
            searchDataLeave();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainLeaveButtonSearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel formDashboardHeaderLabelId;
    public javax.swing.JLabel formDashboardHeaderLabelNik;
    private javax.swing.JLabel formDashboardHeaderLable;
    private javax.swing.JLabel formDashboardLabelFooter2;
    private javax.swing.JButton formDashboardMainAttendanceButtonSearch;
    private javax.swing.JButton formDashboardMainAttendanceCheckin;
    private javax.swing.JButton formDashboardMainAttendanceCheckout;
    private com.toedter.calendar.JDateChooser formDashboardMainAttendanceJDateChooseFrom;
    private com.toedter.calendar.JDateChooser formDashboardMainAttendanceJDateChooseTo;
    private javax.swing.JLabel formDashboardMainAttendanceLebelFrom;
    private javax.swing.JLabel formDashboardMainAttendanceLebelTo;
    private javax.swing.JPanel formDashboardMainAttendancePanel;
    private javax.swing.JPanel formDashboardMainAttendancePanelTable;
    private javax.swing.JTable formDashboardMainAttendanceTable;
    private javax.swing.JButton formDashboardMainAttendanceViewMore;
    private javax.swing.JButton formDashboardMainButtonApproval;
    private javax.swing.JButton formDashboardMainButtonEmployee;
    private javax.swing.JButton formDashboardMainButtonLogout;
    private javax.swing.JButton formDashboardMainButtonReport;
    private javax.swing.JLabel formDashboardMainLabelFullName;
    private javax.swing.JButton formDashboardMainLeaveButtonSearch;
    private com.toedter.calendar.JDateChooser formDashboardMainLeaveJDateChooseFrom;
    private com.toedter.calendar.JDateChooser formDashboardMainLeaveJDateChooseTo;
    private javax.swing.JLabel formDashboardMainLeaveLebelFrom;
    private javax.swing.JLabel formDashboardMainLeaveLebelTo;
    private javax.swing.JPanel formDashboardMainLeavePanel;
    private javax.swing.JPanel formDashboardMainLeavePanelTable;
    private javax.swing.JButton formDashboardMainLeaveRequest;
    private javax.swing.JTable formDashboardMainLeaveTable;
    private javax.swing.JButton formDashboardMainLeaveView;
    private javax.swing.JPanel formDashboardMainPayslipPanelTable;
    private javax.swing.JTable formDashboardMainPayslipTable;
    private javax.swing.JButton formDashboardMainPayslipView;
    private javax.swing.JPanel formDashboardPanelFooter;
    private javax.swing.JPanel formDashboardPanelHeader;
    private javax.swing.JPanel formDashboardPanelMain;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
