package form;

import javax.swing.JOptionPane;
import config.Constanta;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import static java.util.stream.Collectors.toMap;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Attachment;
import model.Attendance;
import model.Employee;
import model.Payslip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 *
 */
public class GeneratePayslip extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public GeneratePayslip() {
        initComponents();
        formGeneratePayslipHeaderLabelId.setVisible(false);
        formGeneratePayslipHeaderLabelNik.setVisible(false);
        formGeneratePayslipHeaderLabelNikLeave.setVisible(false);
        formGeneratePayslipHeaderLabelIdLeave.setVisible(false);
        formGeneratePayslipHeaderLabelNikLeave.setText(Constanta.Default.DEFAULT_VALUE);
        formGeneratePayslipHeaderLabelIdLeave.setText(Constanta.Default.DEFAULT_VALUE);
        bindYear();
        bindMonth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formGeneratePayslipPanelHeader = new javax.swing.JPanel();
        formGeneratePayslipHeaderLable = new javax.swing.JLabel();
        formGeneratePayslipHeaderLabelId = new javax.swing.JLabel();
        formGeneratePayslipHeaderLabelNikLeave = new javax.swing.JLabel();
        formGeneratePayslipHeaderLabelIdLeave = new javax.swing.JLabel();
        formGeneratePayslipHeaderLabelNik = new javax.swing.JLabel();
        formGeneratePayslipPanelFooter = new javax.swing.JPanel();
        formGeneratePayslipLabelFooter2 = new javax.swing.JLabel();
        formGeneratePayslipPanelMain = new javax.swing.JPanel();
        formGeneratePayslipMainLabelFullNameUser = new javax.swing.JLabel();
        formGeneratePayslipMainButtonBack = new javax.swing.JButton();
        formGeneratePayslipMainButtonLogout = new javax.swing.JButton();
        formGeneratePayslipMainPanelForm = new javax.swing.JPanel();
        formGeneratePayslipMainButtonGenerate = new javax.swing.JPanel();
        formGeneratePayslipMainButtonSubmit = new javax.swing.JButton();
        formGeneratePayslipMainButtonSubmit1 = new javax.swing.JButton();
        formGeneratePayslipMainLabelFullName = new javax.swing.JLabel();
        formGeneratePayslipMainValueFullName = new javax.swing.JLabel();
        formGeneratePayslipMainLabelNik = new javax.swing.JLabel();
        formGeneratePayslipMainValueNik = new javax.swing.JLabel();
        formGeneratePayslipMainLabelPeriode = new javax.swing.JLabel();
        formGeneratePayslipMainComboBoxYear = new javax.swing.JComboBox<>();
        formGeneratePayslipMainComboBoxMonth = new javax.swing.JComboBox<>();
        formGeneratePayslipMainLabelPosition = new javax.swing.JLabel();
        formGeneratePayslipMainValuePosition = new javax.swing.JLabel();
        formGeneratePayslipMainLabelBasicSalary = new javax.swing.JLabel();
        formGeneratePayslipMainValueBasicSalary = new javax.swing.JLabel();
        formGeneratePayslipMainLabelOvertimeSalary = new javax.swing.JLabel();
        formGeneratePayslipMainValueOvertimeSalary = new javax.swing.JLabel();
        formGeneratePayslipMainLabelWorkingHours = new javax.swing.JLabel();
        formGeneratePayslipMainValueWorkingHours = new javax.swing.JLabel();
        formGeneratePayslipMainLabelPerDays = new javax.swing.JLabel();
        formGeneratePayslipMainValueWorkingDays = new javax.swing.JLabel();
        formGeneratePayslipMainLabelWorkingDays = new javax.swing.JLabel();
        formGeneratePayslipMainLabelOvertimeHours = new javax.swing.JLabel();
        formGeneratePayslipMainValueOvertimeHours = new javax.swing.JLabel();
        formGeneratePayslipMainLabelBasicCuts = new javax.swing.JLabel();
        formGeneratePayslipMainValueBasicCuts = new javax.swing.JLabel();
        formGeneratePayslipMainLabelTaxCuts = new javax.swing.JLabel();
        formGeneratePayslipMainValueTaxCuts = new javax.swing.JLabel();
        formGeneratePayslipMainLabelNetSalary = new javax.swing.JLabel();
        formGeneratePayslipMainValueNetSalary = new javax.swing.JLabel();
        formGeneratePayslipMainPanelFiles = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        formGeneratePayslipMainTablePayslip = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frameEmployee"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        formGeneratePayslipPanelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formGeneratePayslipPanelHeader.setPreferredSize(new java.awt.Dimension(1280, 70));

        formGeneratePayslipHeaderLable.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        formGeneratePayslipHeaderLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formGeneratePayslipHeaderLable.setText("Generate Payslip");

        formGeneratePayslipHeaderLabelId.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formGeneratePayslipHeaderLabelId.setText("Id");
        formGeneratePayslipHeaderLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formGeneratePayslipHeaderLabelNikLeave.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formGeneratePayslipHeaderLabelNikLeave.setText("IsUpdate");
        formGeneratePayslipHeaderLabelNikLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formGeneratePayslipHeaderLabelIdLeave.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formGeneratePayslipHeaderLabelIdLeave.setText("IdEmployee");
        formGeneratePayslipHeaderLabelIdLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formGeneratePayslipHeaderLabelNik.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formGeneratePayslipHeaderLabelNik.setText("Nik");
        formGeneratePayslipHeaderLabelNik.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout formGeneratePayslipPanelHeaderLayout = new javax.swing.GroupLayout(formGeneratePayslipPanelHeader);
        formGeneratePayslipPanelHeader.setLayout(formGeneratePayslipPanelHeaderLayout);
        formGeneratePayslipPanelHeaderLayout.setHorizontalGroup(
            formGeneratePayslipPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGeneratePayslipPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formGeneratePayslipPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formGeneratePayslipHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formGeneratePayslipPanelHeaderLayout.createSequentialGroup()
                        .addComponent(formGeneratePayslipHeaderLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formGeneratePayslipHeaderLabelNikLeave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formGeneratePayslipHeaderLabelIdLeave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formGeneratePayslipHeaderLabelNik)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formGeneratePayslipPanelHeaderLayout.setVerticalGroup(
            formGeneratePayslipPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGeneratePayslipPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formGeneratePayslipHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formGeneratePayslipPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formGeneratePayslipHeaderLabelId)
                    .addComponent(formGeneratePayslipHeaderLabelNikLeave)
                    .addComponent(formGeneratePayslipHeaderLabelIdLeave)
                    .addComponent(formGeneratePayslipHeaderLabelNik)))
        );

        formGeneratePayslipHeaderLable.getAccessibleContext().setAccessibleDescription("");

        formGeneratePayslipPanelFooter.setPreferredSize(new java.awt.Dimension(1024, 75));

        formGeneratePayslipLabelFooter2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        formGeneratePayslipLabelFooter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formGeneratePayslipLabelFooter2.setText("Employee Content Management System CopyRight ©2021");

        javax.swing.GroupLayout formGeneratePayslipPanelFooterLayout = new javax.swing.GroupLayout(formGeneratePayslipPanelFooter);
        formGeneratePayslipPanelFooter.setLayout(formGeneratePayslipPanelFooterLayout);
        formGeneratePayslipPanelFooterLayout.setHorizontalGroup(
            formGeneratePayslipPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGeneratePayslipPanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formGeneratePayslipLabelFooter2, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
                .addContainerGap())
        );
        formGeneratePayslipPanelFooterLayout.setVerticalGroup(
            formGeneratePayslipPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGeneratePayslipPanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formGeneratePayslipLabelFooter2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formGeneratePayslipPanelMain.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formGeneratePayslipMainLabelFullNameUser.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        formGeneratePayslipMainLabelFullNameUser.setText("FullName");

        formGeneratePayslipMainButtonBack.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainButtonBack.setText("Back");
        formGeneratePayslipMainButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formGeneratePayslipMainButtonBackActionPerformed(evt);
            }
        });
        formGeneratePayslipMainButtonBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formGeneratePayslipMainButtonBackKeyPressed(evt);
            }
        });

        formGeneratePayslipMainButtonLogout.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainButtonLogout.setText("Logout");
        formGeneratePayslipMainButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formGeneratePayslipMainButtonLogoutActionPerformed(evt);
            }
        });
        formGeneratePayslipMainButtonLogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formGeneratePayslipMainButtonLogoutKeyPressed(evt);
            }
        });

        formGeneratePayslipMainPanelForm.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        formGeneratePayslipMainButtonSubmit.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainButtonSubmit.setText("Submit");
        formGeneratePayslipMainButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formGeneratePayslipMainButtonSubmitActionPerformed(evt);
            }
        });
        formGeneratePayslipMainButtonSubmit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formGeneratePayslipMainButtonSubmitKeyPressed(evt);
            }
        });

        formGeneratePayslipMainButtonSubmit1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainButtonSubmit1.setText("Generate");
        formGeneratePayslipMainButtonSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formGeneratePayslipMainButtonSubmit1ActionPerformed(evt);
            }
        });
        formGeneratePayslipMainButtonSubmit1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formGeneratePayslipMainButtonSubmit1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout formGeneratePayslipMainButtonGenerateLayout = new javax.swing.GroupLayout(formGeneratePayslipMainButtonGenerate);
        formGeneratePayslipMainButtonGenerate.setLayout(formGeneratePayslipMainButtonGenerateLayout);
        formGeneratePayslipMainButtonGenerateLayout.setHorizontalGroup(
            formGeneratePayslipMainButtonGenerateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formGeneratePayslipMainButtonGenerateLayout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addComponent(formGeneratePayslipMainButtonSubmit1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(formGeneratePayslipMainButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339))
        );
        formGeneratePayslipMainButtonGenerateLayout.setVerticalGroup(
            formGeneratePayslipMainButtonGenerateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formGeneratePayslipMainButtonGenerateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formGeneratePayslipMainButtonGenerateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formGeneratePayslipMainButtonSubmit)
                    .addComponent(formGeneratePayslipMainButtonSubmit1))
                .addContainerGap())
        );

        formGeneratePayslipMainLabelFullName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelFullName.setText("Full Name");

        formGeneratePayslipMainValueFullName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainValueFullName.setText("FullName");

        formGeneratePayslipMainLabelNik.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelNik.setText("Nik");

        formGeneratePayslipMainValueNik.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainValueNik.setText("Nik");

        formGeneratePayslipMainLabelPeriode.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelPeriode.setText("Periode");

        formGeneratePayslipMainComboBoxYear.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formGeneratePayslipMainComboBoxMonth.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formGeneratePayslipMainLabelPosition.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelPosition.setText("Position");

        formGeneratePayslipMainValuePosition.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainValuePosition.setText("Position");

        formGeneratePayslipMainLabelBasicSalary.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelBasicSalary.setText("Basic Salary");

        formGeneratePayslipMainValueBasicSalary.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainValueBasicSalary.setText("BasicSalary");

        formGeneratePayslipMainLabelOvertimeSalary.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelOvertimeSalary.setText("Overtime Salary");

        formGeneratePayslipMainValueOvertimeSalary.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainValueOvertimeSalary.setText("OvertimeSalary");

        formGeneratePayslipMainLabelWorkingHours.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelWorkingHours.setText("Working Hours");

        formGeneratePayslipMainValueWorkingHours.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainValueWorkingHours.setText("WorkingHours");

        formGeneratePayslipMainLabelPerDays.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelPerDays.setText("/");

        formGeneratePayslipMainValueWorkingDays.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainValueWorkingDays.setText("Days");

        formGeneratePayslipMainLabelWorkingDays.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelWorkingDays.setText("Days");

        formGeneratePayslipMainLabelOvertimeHours.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelOvertimeHours.setText("Overtime Hours");

        formGeneratePayslipMainValueOvertimeHours.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainValueOvertimeHours.setText("OvertimeHours");

        formGeneratePayslipMainLabelBasicCuts.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelBasicCuts.setText("Basic Cuts");

        formGeneratePayslipMainValueBasicCuts.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainValueBasicCuts.setText("BasicCuts");

        formGeneratePayslipMainLabelTaxCuts.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainLabelTaxCuts.setText("Tax Cuts");

        formGeneratePayslipMainValueTaxCuts.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formGeneratePayslipMainValueTaxCuts.setText("Tax Cuts");

        formGeneratePayslipMainLabelNetSalary.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        formGeneratePayslipMainLabelNetSalary.setText("Net Salary");

        formGeneratePayslipMainValueNetSalary.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        formGeneratePayslipMainValueNetSalary.setText("NetSalary");

        javax.swing.GroupLayout formGeneratePayslipMainPanelFormLayout = new javax.swing.GroupLayout(formGeneratePayslipMainPanelForm);
        formGeneratePayslipMainPanelForm.setLayout(formGeneratePayslipMainPanelFormLayout);
        formGeneratePayslipMainPanelFormLayout.setHorizontalGroup(
            formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formGeneratePayslipMainButtonGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                        .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                                .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(formGeneratePayslipMainLabelWorkingHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(formGeneratePayslipMainLabelBasicSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(formGeneratePayslipMainLabelFullName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(formGeneratePayslipMainLabelNik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(74, 74, 74))
                            .addGroup(formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                                .addComponent(formGeneratePayslipMainLabelBasicCuts, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addGap(102, 102, 102)))
                        .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formGeneratePayslipMainValueBasicCuts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formGeneratePayslipMainValueNik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formGeneratePayslipMainValueBasicSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formGeneratePayslipMainValueFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addGroup(formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                                .addComponent(formGeneratePayslipMainValueWorkingHours)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(formGeneratePayslipMainLabelPerDays)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formGeneratePayslipMainValueWorkingDays)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formGeneratePayslipMainLabelWorkingDays)))
                        .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                                        .addGap(208, 208, 208)
                                        .addComponent(formGeneratePayslipMainValueNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(formGeneratePayslipMainValueTaxCuts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(formGeneratePayslipMainValueOvertimeHours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(formGeneratePayslipMainLabelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formGeneratePayslipMainLabelPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formGeneratePayslipMainLabelOvertimeSalary)
                                    .addComponent(formGeneratePayslipMainLabelOvertimeHours)
                                    .addComponent(formGeneratePayslipMainLabelTaxCuts)
                                    .addComponent(formGeneratePayslipMainLabelNetSalary))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(formGeneratePayslipMainValuePosition, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                                            .addComponent(formGeneratePayslipMainComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(formGeneratePayslipMainComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(formGeneratePayslipMainValueOvertimeSalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        formGeneratePayslipMainPanelFormLayout.setVerticalGroup(
            formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                        .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formGeneratePayslipMainComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formGeneratePayslipMainComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(formGeneratePayslipMainValuePosition)
                        .addGap(18, 18, 18)
                        .addComponent(formGeneratePayslipMainValueOvertimeSalary))
                    .addGroup(formGeneratePayslipMainPanelFormLayout.createSequentialGroup()
                        .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formGeneratePayslipMainValueFullName)
                            .addComponent(formGeneratePayslipMainLabelPeriode)
                            .addComponent(formGeneratePayslipMainLabelFullName))
                        .addGap(20, 20, 20)
                        .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formGeneratePayslipMainValueNik)
                            .addComponent(formGeneratePayslipMainLabelPosition)
                            .addComponent(formGeneratePayslipMainLabelNik))
                        .addGap(18, 18, 18)
                        .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formGeneratePayslipMainValueBasicSalary)
                            .addComponent(formGeneratePayslipMainLabelOvertimeSalary)
                            .addComponent(formGeneratePayslipMainLabelBasicSalary))))
                .addGap(18, 18, 18)
                .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formGeneratePayslipMainLabelWorkingHours)
                    .addComponent(formGeneratePayslipMainValueOvertimeHours)
                    .addComponent(formGeneratePayslipMainValueWorkingHours)
                    .addComponent(formGeneratePayslipMainLabelOvertimeHours)
                    .addComponent(formGeneratePayslipMainLabelPerDays)
                    .addComponent(formGeneratePayslipMainValueWorkingDays)
                    .addComponent(formGeneratePayslipMainLabelWorkingDays))
                .addGap(18, 18, 18)
                .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formGeneratePayslipMainValueTaxCuts)
                    .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formGeneratePayslipMainLabelTaxCuts)
                        .addComponent(formGeneratePayslipMainValueBasicCuts)
                        .addComponent(formGeneratePayslipMainLabelBasicCuts)))
                .addGap(18, 18, 18)
                .addGroup(formGeneratePayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formGeneratePayslipMainValueNetSalary)
                    .addComponent(formGeneratePayslipMainLabelNetSalary))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(formGeneratePayslipMainButtonGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        formGeneratePayslipMainPanelFiles.setBorder(javax.swing.BorderFactory.createTitledBorder("History Payslip"));

        formGeneratePayslipMainTablePayslip.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        formGeneratePayslipMainTablePayslip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nik", "File Name", "Periode", "Net Salary", "Working Hours"
            }
        ));
        formGeneratePayslipMainTablePayslip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formGeneratePayslipMainTablePayslipMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(formGeneratePayslipMainTablePayslip);

        javax.swing.GroupLayout formGeneratePayslipMainPanelFilesLayout = new javax.swing.GroupLayout(formGeneratePayslipMainPanelFiles);
        formGeneratePayslipMainPanelFiles.setLayout(formGeneratePayslipMainPanelFilesLayout);
        formGeneratePayslipMainPanelFilesLayout.setHorizontalGroup(
            formGeneratePayslipMainPanelFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGeneratePayslipMainPanelFilesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        formGeneratePayslipMainPanelFilesLayout.setVerticalGroup(
            formGeneratePayslipMainPanelFilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGeneratePayslipMainPanelFilesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout formGeneratePayslipPanelMainLayout = new javax.swing.GroupLayout(formGeneratePayslipPanelMain);
        formGeneratePayslipPanelMain.setLayout(formGeneratePayslipPanelMainLayout);
        formGeneratePayslipPanelMainLayout.setHorizontalGroup(
            formGeneratePayslipPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGeneratePayslipPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formGeneratePayslipPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formGeneratePayslipPanelMainLayout.createSequentialGroup()
                        .addComponent(formGeneratePayslipMainLabelFullNameUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formGeneratePayslipMainButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formGeneratePayslipMainButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formGeneratePayslipMainPanelFiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(formGeneratePayslipPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formGeneratePayslipPanelMainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formGeneratePayslipMainPanelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        formGeneratePayslipPanelMainLayout.setVerticalGroup(
            formGeneratePayslipPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formGeneratePayslipPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formGeneratePayslipPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formGeneratePayslipMainButtonLogout)
                    .addComponent(formGeneratePayslipMainLabelFullNameUser)
                    .addComponent(formGeneratePayslipMainButtonBack))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(formGeneratePayslipMainPanelFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(formGeneratePayslipPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formGeneratePayslipPanelMainLayout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(formGeneratePayslipMainPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(167, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formGeneratePayslipPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formGeneratePayslipPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formGeneratePayslipPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formGeneratePayslipPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formGeneratePayslipPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formGeneratePayslipPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        formGeneratePayslipPanelHeader.getAccessibleContext().setAccessibleName("");
        formGeneratePayslipPanelHeader.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    LocalDateTime localDateTimeNow = LocalDateTime.now();
    DateTimeFormatter DATETIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
    private List<String> access_menu = new ArrayList<>();
    private String full_name;
    public List<Attachment> list_attachments = new ArrayList<>();
    private Payslip payslip = new Payslip();

    public void setLabelId(String text) {
        formGeneratePayslipHeaderLabelId.setText(text);
    }

    public void setLabelNik(String text) {
        formGeneratePayslipHeaderLabelNik.setText(text);
    }

    public String getFullName() {
        return full_name;
    }

    public void setFullName(String text) {
        this.full_name = text;
        formGeneratePayslipMainLabelFullNameUser.setText("Welcome " + text + ",");
    }

    public List<String> getAccessMenu() {
        return access_menu;
    }

    public void setAccessMenu(List<String> value) {
        this.access_menu = value;
    }

    public void setListAttachment(List<Attachment> value) {
        this.list_attachments = value;
    }

    public List<Attachment> getListAttachment() {
        return list_attachments;
    }

    public void setPayslip(Payslip value) {
        this.payslip = value;
    }

    public Payslip getPayslip() {
        return payslip;
    }

    public void loadDataPayslip(String username) throws SQLException {
        List<Payslip> listPayslip;

        listPayslip = Payslip.listParams()
                .withUsername(username)
                .withPeriode(null)
                .get();

        DefaultTableModel defaultTableModel = (DefaultTableModel) formGeneratePayslipMainTablePayslip.getModel();
        defaultTableModel.setRowCount(0);
        Object[] rows = new Object[6];

        TableColumnModel tableColumnModel = formGeneratePayslipMainTablePayslip.getColumnModel();
        tableColumnModel.getColumn(0).setMaxWidth(0);
        tableColumnModel.getColumn(0).setMinWidth(0);

        for (int i = 0; i < listPayslip.size(); i++) {
            rows[0] = listPayslip.get(i).getId();
            rows[1] = listPayslip.get(i).getUsername();
            rows[2] = listPayslip.get(i).getFullName();
            rows[3] = listPayslip.get(i).getPeriode();
            rows[4] = String.format("%.0f", listPayslip.get(i).getNetSalary());
            rows[5] = String.format("%.0f", listPayslip.get(i).getWorkingHour() + listPayslip.get(i).getOvertimeHour());

            defaultTableModel.addRow(rows);
        }
        formGeneratePayslipMainTablePayslip.setAutoCreateRowSorter(true);

    }

    private void bindYear() {
        try {
            for (int years = Calendar.getInstance().get(Calendar.YEAR); years >= 1980; years--) {
                formGeneratePayslipMainComboBoxYear.addItem("" + years);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }

    private void bindMonth() {
        try {
            Constanta.Default constantaDefault = new Constanta.Default();
            HashMap<String, Integer> map = constantaDefault.getMonth();
            Map<String, Integer> sortedByValue = map.entrySet()
                    .stream()
                    .sorted(Map.Entry.<String, Integer>comparingByValue())
                    .collect(toMap(Map.Entry::getKey, Map.Entry::getValue, (e1, e2) -> e1, LinkedHashMap::new));
            sortedByValue.entrySet().forEach((entry) -> {
                formGeneratePayslipMainComboBoxMonth.addItem(entry.getKey());
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }

    @SuppressWarnings("empty-statement")
    private void generate() throws SQLException {
        Attendance attendance = new Attendance();
        Payslip payslip = new Payslip();
        Constanta.Default constantaDefault = new Constanta.Default();
        DecimalFormat decimalFormat = new DecimalFormat("#.00");
        DecimalFormat integerFormat = new DecimalFormat("#");

        String periode = formGeneratePayslipMainComboBoxYear.getSelectedItem() + "-" + constantaDefault.getMonth(formGeneratePayslipMainComboBoxMonth.getSelectedItem().toString());
        String nik = formGeneratePayslipMainValueNik.getText();
        List<Attendance> listAttendance = attendance.getByUsernameAndPeriode(nik, periode);

        List<Payslip> listPayslip = payslip.searchByUsernameAndPeriode(nik, periode);
        boolean isAlready = listPayslip.size() > 0;

        if (!isAlready) {
            if (listAttendance.size() > 0) {
                int totalWorking = 0;
                int totalOvertime = 0;
                int totalPresent = 0;
                int totalAbsen = 0;
                for (Attendance item : listAttendance) {
                    totalWorking += item.getDuration();
                    totalPresent++;
                    if (item.getOvertime() > 0) {
                        totalOvertime += item.getOvertime();
                    }
                    if (item.getAbsen() > 0) {
                        totalAbsen++;
                    }
                }

                Employee employee = new Employee();
                employee = employee.getByNik(nik);
                float basicSalary = employee.getBasicSalary();
                float overtimeSalary = employee.getBasicSalary() / Constanta.Default.DEFAULT_NORMAL_WORKING_DAYS * totalOvertime;
                if (totalPresent < Constanta.Default.DEFAULT_NORMAL_WORKING_DAYS) {
                    totalAbsen += (Constanta.Default.DEFAULT_NORMAL_WORKING_DAYS - totalPresent);
                }
                float basicCuts = basicSalary / Constanta.Default.DEFAULT_NORMAL_WORKING_DAYS * totalAbsen;
                float taxCuts = basicSalary * Constanta.Default.DEFAULT_PPN_TAX / 100;
                float netSalary = (basicSalary + overtimeSalary) - (basicCuts + taxCuts);
                if(netSalary <= 0){
                    netSalary = 0;
                }
                
                formGeneratePayslipMainValueBasicSalary.setText(decimalFormat.format(basicSalary));
                formGeneratePayslipMainValueOvertimeSalary.setText(decimalFormat.format(overtimeSalary));
                formGeneratePayslipMainValueWorkingHours.setText(integerFormat.format(totalWorking));
                formGeneratePayslipMainValueWorkingDays.setText(integerFormat.format(totalPresent));
                formGeneratePayslipMainValueOvertimeHours.setText(integerFormat.format(totalOvertime));
                formGeneratePayslipMainValueBasicCuts.setText(decimalFormat.format(basicCuts));
                formGeneratePayslipMainValueTaxCuts.setText(decimalFormat.format(taxCuts));
                formGeneratePayslipMainValueNetSalary.setText(decimalFormat.format(netSalary));

                payslip = new Payslip();
                payslip.setUsername(nik);
                payslip.setPeriode(periode);
                payslip.setWorkingHour((float) totalWorking);
                payslip.setOvertimeHour((float) totalOvertime);
                payslip.setBasicSalary(basicSalary);
                payslip.setOvertimeSalary(overtimeSalary);
                payslip.setBasicCuts(basicCuts);
                payslip.setTaxCuts(taxCuts);
                payslip.setNetSalary(netSalary);
                setPayslip(payslip);
                payslip = new Payslip(); //clear
            } else {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_NOT_FOUND);
            }
        } else {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ALREADY);
        }
    }

    public boolean submit() throws SQLException {
        boolean result;
        Payslip payslip = new Payslip();
        result = payslip.create(getPayslip());
        return result;
    }

    public void clear() throws SQLException {
        String username = formGeneratePayslipMainValueNik.getText();
        formGeneratePayslipMainValueBasicSalary.setText("0");
        formGeneratePayslipMainValueOvertimeSalary.setText("0");
        formGeneratePayslipMainValueWorkingHours.setText("0");
        formGeneratePayslipMainValueWorkingDays.setText("0");
        formGeneratePayslipMainValueOvertimeHours.setText("0");
        formGeneratePayslipMainValueBasicCuts.setText("0");
        formGeneratePayslipMainValueTaxCuts.setText("0");
        formGeneratePayslipMainValueNetSalary.setText("0");
        loadDataPayslip(username);
        
        Payslip payslip = new Payslip();
        setPayslip(payslip);
    }

    public void assignValue(Employee employee) {
        try {
            formGeneratePayslipHeaderLabelNikLeave.setText(employee.getNik());
            formGeneratePayslipHeaderLabelIdLeave.setText(employee.getId().toString());
            formGeneratePayslipMainValueFullName.setText(employee.getFirstName() + " " + employee.getLastName());
            formGeneratePayslipMainValueNik.setText(employee.getNik());
            formGeneratePayslipMainValuePosition.setText(employee.getPositionName());
            clear();
            loadDataPayslip(employee.getNik());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }

    private void displayImage(String path, String name) throws IOException {
        JPanel panel = new JPanel();

        BufferedImage image = ImageIO.read(new File(path));
        JLabel label = new JLabel(new ImageIcon(image));
        panel.add(label);

        JFrame.setDefaultLookAndFeelDecorated(true);
        JFrame frame = new JFrame(name);

        frame.add(panel);
        frame.pack();
        frame.setVisible(true);
    }

    private void formGeneratePayslipMainButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formGeneratePayslipMainButtonBackActionPerformed
        // TODO add your handling code here:
        try {
            EmployeePayslipList employeePayslipList = new EmployeePayslipList();
            employeePayslipList.show(true);
            employeePayslipList.setLabelId(formGeneratePayslipHeaderLabelId.getText());
            employeePayslipList.setLabelNik(formGeneratePayslipHeaderLabelNik.getText());
            employeePayslipList.setFullName(getFullName());
            employeePayslipList.setAccessMenu(getAccessMenu());
            employeePayslipList.loadData();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formGeneratePayslipMainButtonBackActionPerformed

    private void formGeneratePayslipMainButtonBackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formGeneratePayslipMainButtonBackKeyPressed
        // TODO add your handling code here:
        try {
            EmployeePayslipList employeePayslipList = new EmployeePayslipList();
            employeePayslipList.show(true);
            employeePayslipList.setLabelId(formGeneratePayslipHeaderLabelId.getText());
            employeePayslipList.setLabelNik(formGeneratePayslipHeaderLabelNik.getText());
            employeePayslipList.setFullName(getFullName());
            employeePayslipList.setAccessMenu(getAccessMenu());
            employeePayslipList.loadData();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formGeneratePayslipMainButtonBackKeyPressed

    private void formGeneratePayslipMainButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formGeneratePayslipMainButtonLogoutActionPerformed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formGeneratePayslipMainButtonLogoutActionPerformed

    private void formGeneratePayslipMainButtonLogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formGeneratePayslipMainButtonLogoutKeyPressed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formGeneratePayslipMainButtonLogoutKeyPressed

    private void formGeneratePayslipMainButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formGeneratePayslipMainButtonSubmitActionPerformed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_SUBMIT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (action == JOptionPane.YES_OPTION) {
                if (!formGeneratePayslipMainValueNetSalary.getText().equals("0")) {
                    if (submit()) {
                        JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
                        loadDataPayslip(getPayslip().getUsername());
                    } else {
                        JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SHOULD_GENERATE);
                }
            }
            clear();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formGeneratePayslipMainButtonSubmitActionPerformed

    private void formGeneratePayslipMainButtonSubmitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formGeneratePayslipMainButtonSubmitKeyPressed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_SUBMIT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (action == JOptionPane.YES_OPTION) {
                if (!formGeneratePayslipMainValueNetSalary.getText().equals("0")) {
                    if (submit()) {
                        JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
                        loadDataPayslip(getPayslip().getUsername());
                    } else {
                        JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SHOULD_GENERATE);
                }
            }
            clear();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formGeneratePayslipMainButtonSubmitKeyPressed

    private void formGeneratePayslipMainTablePayslipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formGeneratePayslipMainTablePayslipMouseClicked
        // TODO add your handling code here:
        try {
            int rowSelected = formGeneratePayslipMainTablePayslip.getSelectedRow();
            String selectedFileName = formGeneratePayslipMainTablePayslip.getValueAt(rowSelected, 2).toString();
            String selectedFilePath = formGeneratePayslipMainTablePayslip.getValueAt(rowSelected, 3).toString();
            displayImage(selectedFilePath, selectedFileName);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formGeneratePayslipMainTablePayslipMouseClicked

    private void formGeneratePayslipMainButtonSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formGeneratePayslipMainButtonSubmit1ActionPerformed
        // TODO add your handling code here:
        try {
            generate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formGeneratePayslipMainButtonSubmit1ActionPerformed

    private void formGeneratePayslipMainButtonSubmit1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formGeneratePayslipMainButtonSubmit1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formGeneratePayslipMainButtonSubmit1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneratePayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneratePayslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel formGeneratePayslipHeaderLabelId;
    public javax.swing.JLabel formGeneratePayslipHeaderLabelIdLeave;
    public javax.swing.JLabel formGeneratePayslipHeaderLabelNik;
    public javax.swing.JLabel formGeneratePayslipHeaderLabelNikLeave;
    private javax.swing.JLabel formGeneratePayslipHeaderLable;
    private javax.swing.JLabel formGeneratePayslipLabelFooter2;
    private javax.swing.JButton formGeneratePayslipMainButtonBack;
    private javax.swing.JPanel formGeneratePayslipMainButtonGenerate;
    private javax.swing.JButton formGeneratePayslipMainButtonLogout;
    private javax.swing.JButton formGeneratePayslipMainButtonSubmit;
    private javax.swing.JButton formGeneratePayslipMainButtonSubmit1;
    private javax.swing.JComboBox<String> formGeneratePayslipMainComboBoxMonth;
    private javax.swing.JComboBox<String> formGeneratePayslipMainComboBoxYear;
    private javax.swing.JLabel formGeneratePayslipMainLabelBasicCuts;
    private javax.swing.JLabel formGeneratePayslipMainLabelBasicSalary;
    private javax.swing.JLabel formGeneratePayslipMainLabelFullName;
    private javax.swing.JLabel formGeneratePayslipMainLabelFullNameUser;
    private javax.swing.JLabel formGeneratePayslipMainLabelNetSalary;
    private javax.swing.JLabel formGeneratePayslipMainLabelNik;
    private javax.swing.JLabel formGeneratePayslipMainLabelOvertimeHours;
    private javax.swing.JLabel formGeneratePayslipMainLabelOvertimeSalary;
    private javax.swing.JLabel formGeneratePayslipMainLabelPerDays;
    private javax.swing.JLabel formGeneratePayslipMainLabelPeriode;
    private javax.swing.JLabel formGeneratePayslipMainLabelPosition;
    private javax.swing.JLabel formGeneratePayslipMainLabelTaxCuts;
    private javax.swing.JLabel formGeneratePayslipMainLabelWorkingDays;
    private javax.swing.JLabel formGeneratePayslipMainLabelWorkingHours;
    private javax.swing.JPanel formGeneratePayslipMainPanelFiles;
    private javax.swing.JPanel formGeneratePayslipMainPanelForm;
    private javax.swing.JTable formGeneratePayslipMainTablePayslip;
    private javax.swing.JLabel formGeneratePayslipMainValueBasicCuts;
    private javax.swing.JLabel formGeneratePayslipMainValueBasicSalary;
    private javax.swing.JLabel formGeneratePayslipMainValueFullName;
    private javax.swing.JLabel formGeneratePayslipMainValueNetSalary;
    private javax.swing.JLabel formGeneratePayslipMainValueNik;
    private javax.swing.JLabel formGeneratePayslipMainValueOvertimeHours;
    private javax.swing.JLabel formGeneratePayslipMainValueOvertimeSalary;
    private javax.swing.JLabel formGeneratePayslipMainValuePosition;
    private javax.swing.JLabel formGeneratePayslipMainValueTaxCuts;
    private javax.swing.JLabel formGeneratePayslipMainValueWorkingDays;
    private javax.swing.JLabel formGeneratePayslipMainValueWorkingHours;
    private javax.swing.JPanel formGeneratePayslipPanelFooter;
    private javax.swing.JPanel formGeneratePayslipPanelHeader;
    private javax.swing.JPanel formGeneratePayslipPanelMain;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
