package form;

import javax.swing.JOptionPane;
import config.Constanta;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Attendance;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 *  
 */
public class LeaveDetail extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LeaveDetail() {
        initComponents();
        formLeaveHeaderLabelId.setVisible(false);
        formLeaveHeaderLabelNik.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formLeavePanelHeader = new javax.swing.JPanel();
        formLeaveHeaderLable = new javax.swing.JLabel();
        formLeaveHeaderLabelId = new javax.swing.JLabel();
        formLeaveHeaderLabelNik = new javax.swing.JLabel();
        formLeavePanelFooter = new javax.swing.JPanel();
        formLeaveLabelFooter2 = new javax.swing.JLabel();
        formLeavePanelMain = new javax.swing.JPanel();
        formLeaveMainLabelFullName = new javax.swing.JLabel();
        formLeaveMainButtonLogout = new javax.swing.JButton();
        formLeaveMainButtonBack = new javax.swing.JButton();
        formLeaveMainLeavePanelTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        formLeaveMainLeaveTable = new javax.swing.JTable();
        formLeaveMainLeaveGenerate = new javax.swing.JButton();
        formLeaveMainLeavePanel = new javax.swing.JPanel();
        formLeaveMainLeaveLebelFullName = new javax.swing.JLabel();
        formLeaveMainLeaveLebelFrom = new javax.swing.JLabel();
        formLeaveMainLeaveLebelTo = new javax.swing.JLabel();
        formLeaveMainLeaveTextFieldFullName = new javax.swing.JTextField();
        formLeaveMainLeaveJDateChooseFrom = new com.toedter.calendar.JDateChooser();
        formLeaveMainLeaveJDateChooseTo = new com.toedter.calendar.JDateChooser();
        formLeaveMainLeaveButtonSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frameEmployee"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        formLeavePanelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formLeavePanelHeader.setPreferredSize(new java.awt.Dimension(1024, 100));

        formLeaveHeaderLable.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        formLeaveHeaderLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formLeaveHeaderLable.setText("Leave Detail");

        formLeaveHeaderLabelId.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formLeaveHeaderLabelId.setText("Id");
        formLeaveHeaderLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formLeaveHeaderLabelNik.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formLeaveHeaderLabelNik.setText("Nik");
        formLeaveHeaderLabelNik.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout formLeavePanelHeaderLayout = new javax.swing.GroupLayout(formLeavePanelHeader);
        formLeavePanelHeader.setLayout(formLeavePanelHeaderLayout);
        formLeavePanelHeaderLayout.setHorizontalGroup(
            formLeavePanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLeavePanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formLeavePanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formLeaveHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                    .addGroup(formLeavePanelHeaderLayout.createSequentialGroup()
                        .addComponent(formLeaveHeaderLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formLeaveHeaderLabelNik)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formLeavePanelHeaderLayout.setVerticalGroup(
            formLeavePanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLeavePanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formLeaveHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLeavePanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formLeaveHeaderLabelId)
                    .addComponent(formLeaveHeaderLabelNik)))
        );

        formLeaveHeaderLable.getAccessibleContext().setAccessibleDescription("");

        formLeavePanelFooter.setPreferredSize(new java.awt.Dimension(1024, 75));

        formLeaveLabelFooter2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        formLeaveLabelFooter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formLeaveLabelFooter2.setText("Employee Content Management System CopyRight ©2021");

        javax.swing.GroupLayout formLeavePanelFooterLayout = new javax.swing.GroupLayout(formLeavePanelFooter);
        formLeavePanelFooter.setLayout(formLeavePanelFooterLayout);
        formLeavePanelFooterLayout.setHorizontalGroup(
            formLeavePanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLeavePanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formLeaveLabelFooter2, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                .addContainerGap())
        );
        formLeavePanelFooterLayout.setVerticalGroup(
            formLeavePanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLeavePanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formLeaveLabelFooter2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formLeaveMainLabelFullName.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        formLeaveMainLabelFullName.setText("FullName");

        formLeaveMainButtonLogout.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formLeaveMainButtonLogout.setText("Logout");
        formLeaveMainButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formLeaveMainButtonLogoutActionPerformed(evt);
            }
        });
        formLeaveMainButtonLogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formLeaveMainButtonLogoutKeyPressed(evt);
            }
        });

        formLeaveMainButtonBack.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formLeaveMainButtonBack.setText("Back");
        formLeaveMainButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formLeaveMainButtonBackActionPerformed(evt);
            }
        });
        formLeaveMainButtonBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formLeaveMainButtonBackKeyPressed(evt);
            }
        });

        formLeaveMainLeavePanelTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Attendance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 11))); // NOI18N

        formLeaveMainLeaveTable.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        formLeaveMainLeaveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nik", "Full Name", "Check In", "Check Out", "Location", "Duration", "Status", "Information"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        formLeaveMainLeaveTable.setColumnSelectionAllowed(true);
        formLeaveMainLeaveTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formLeaveMainLeaveTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formLeaveMainLeaveTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(formLeaveMainLeaveTable);
        formLeaveMainLeaveTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (formLeaveMainLeaveTable.getColumnModel().getColumnCount() > 0) {
            formLeaveMainLeaveTable.getColumnModel().getColumn(0).setHeaderValue("Id");
            formLeaveMainLeaveTable.getColumnModel().getColumn(1).setHeaderValue("Nik");
            formLeaveMainLeaveTable.getColumnModel().getColumn(2).setHeaderValue("Full Name");
            formLeaveMainLeaveTable.getColumnModel().getColumn(3).setHeaderValue("Check In");
            formLeaveMainLeaveTable.getColumnModel().getColumn(4).setHeaderValue("Check Out");
            formLeaveMainLeaveTable.getColumnModel().getColumn(5).setHeaderValue("Location");
            formLeaveMainLeaveTable.getColumnModel().getColumn(6).setHeaderValue("Duration");
            formLeaveMainLeaveTable.getColumnModel().getColumn(7).setHeaderValue("Status");
            formLeaveMainLeaveTable.getColumnModel().getColumn(8).setHeaderValue("Information");
        }

        formLeaveMainLeaveGenerate.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formLeaveMainLeaveGenerate.setText("Generate Attendance Report");
        formLeaveMainLeaveGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formLeaveMainLeaveGenerateActionPerformed(evt);
            }
        });
        formLeaveMainLeaveGenerate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formLeaveMainLeaveGenerateKeyPressed(evt);
            }
        });

        formLeaveMainLeaveLebelFullName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formLeaveMainLeaveLebelFullName.setText("Full Name");

        formLeaveMainLeaveLebelFrom.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formLeaveMainLeaveLebelFrom.setText("From");

        formLeaveMainLeaveLebelTo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formLeaveMainLeaveLebelTo.setText("To");

        formLeaveMainLeaveTextFieldFullName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formLeaveMainLeaveJDateChooseFrom.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formLeaveMainLeaveJDateChooseTo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formLeaveMainLeaveButtonSearch.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formLeaveMainLeaveButtonSearch.setText("Search");
        formLeaveMainLeaveButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formLeaveMainLeaveButtonSearchActionPerformed(evt);
            }
        });
        formLeaveMainLeaveButtonSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formLeaveMainLeaveButtonSearchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout formLeaveMainLeavePanelLayout = new javax.swing.GroupLayout(formLeaveMainLeavePanel);
        formLeaveMainLeavePanel.setLayout(formLeaveMainLeavePanelLayout);
        formLeaveMainLeavePanelLayout.setHorizontalGroup(
            formLeaveMainLeavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLeaveMainLeavePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formLeaveMainLeaveLebelFullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formLeaveMainLeaveTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formLeaveMainLeaveLebelFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formLeaveMainLeaveJDateChooseFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formLeaveMainLeaveLebelTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formLeaveMainLeaveJDateChooseTo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formLeaveMainLeaveButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        formLeaveMainLeavePanelLayout.setVerticalGroup(
            formLeaveMainLeavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLeaveMainLeavePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formLeaveMainLeavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formLeaveMainLeaveLebelFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formLeaveMainLeaveButtonSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formLeaveMainLeaveJDateChooseTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formLeaveMainLeaveJDateChooseFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLeaveMainLeavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formLeaveMainLeaveTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(formLeaveMainLeaveLebelFullName))
                    .addComponent(formLeaveMainLeaveLebelTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout formLeaveMainLeavePanelTableLayout = new javax.swing.GroupLayout(formLeaveMainLeavePanelTable);
        formLeaveMainLeavePanelTable.setLayout(formLeaveMainLeavePanelTableLayout);
        formLeaveMainLeavePanelTableLayout.setHorizontalGroup(
            formLeaveMainLeavePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLeaveMainLeavePanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formLeaveMainLeavePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formLeaveMainLeavePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formLeaveMainLeavePanelTableLayout.createSequentialGroup()
                        .addGroup(formLeaveMainLeavePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formLeaveMainLeaveGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
        formLeaveMainLeavePanelTableLayout.setVerticalGroup(
            formLeaveMainLeavePanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLeaveMainLeavePanelTableLayout.createSequentialGroup()
                .addComponent(formLeaveMainLeavePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formLeaveMainLeaveGenerate)
                .addContainerGap())
        );

        javax.swing.GroupLayout formLeavePanelMainLayout = new javax.swing.GroupLayout(formLeavePanelMain);
        formLeavePanelMain.setLayout(formLeavePanelMainLayout);
        formLeavePanelMainLayout.setHorizontalGroup(
            formLeavePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLeavePanelMainLayout.createSequentialGroup()
                .addGroup(formLeavePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formLeavePanelMainLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(formLeaveMainLabelFullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formLeaveMainButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formLeaveMainButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formLeavePanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(formLeaveMainLeavePanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formLeavePanelMainLayout.setVerticalGroup(
            formLeavePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLeavePanelMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(formLeavePanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formLeaveMainButtonLogout)
                    .addComponent(formLeaveMainLabelFullName)
                    .addComponent(formLeaveMainButtonBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formLeaveMainLeavePanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formLeavePanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(formLeavePanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(formLeavePanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formLeavePanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formLeavePanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formLeavePanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        formLeavePanelHeader.getAccessibleContext().setAccessibleName("");
        formLeavePanelHeader.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    LocalDateTime localDateTimeNow = LocalDateTime.now();
    DateTimeFormatter DATETIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    DateTimeFormatter DATETIME_PDF_FORMATTER = DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
    private List<String> access_menu = new ArrayList<>();
    private String full_name;

    public void setLabelId(String text) {
        formLeaveHeaderLabelId.setText(text);
    }

    public void setLabelNik(String text) {
        formLeaveHeaderLabelNik.setText(text);
    }

    public String getFullName() {
        return full_name;
    }

    public void setFullName(String text) {
        this.full_name = text;
        formLeaveMainLabelFullName.setText("Welcome " + text + ",");
    }

    public List<String> getAccessMenu() {
        return access_menu;
    }

    public void setAccessMenu(List<String> value) {
        this.access_menu = value;
    }

    private List<Attendance> list_attendance;

    private void setListAttendance(List<Attendance> value) {
        this.list_attendance = value;
    }

    private List<Attendance> getListAttendance() {
        return list_attendance;
    }

    public void loadDataAttendance() {
        try {
            List<Attendance> listAttendance;
            if (formLeaveHeaderLabelNik.getText().equals("hrd")
                    || formLeaveHeaderLabelNik.getText().equals("admin")) {
                listAttendance = Attendance.listParams()
                        .withUsername("")
                        .withDateFrom(null)
                        .withDateTo(null)
                        .build();
            } else {
                listAttendance = Attendance.listParams()
                        .withUsername(formLeaveHeaderLabelNik.getText())
                        .withDateFrom(null)
                        .withDateTo(null)
                        .build();
            }

            DefaultTableModel defaultTableModel = (DefaultTableModel) formLeaveMainLeaveTable.getModel();
            defaultTableModel.setRowCount(0);
            Object[] rows = new Object[9];
            for (int i = 0; i < listAttendance.size(); i++) {
                TableColumnModel tableColumnModel = formLeaveMainLeaveTable.getColumnModel();
                tableColumnModel.getColumn(0).setMaxWidth(0);
                tableColumnModel.getColumn(0).setMinWidth(0);

                rows[0] = listAttendance.get(i).getId();
                rows[1] = listAttendance.get(i).getUsername();
                rows[2] = listAttendance.get(i).getFullName();
                rows[3] = listAttendance.get(i).getCheckIn();
                rows[4] = listAttendance.get(i).getCheckOut();
                rows[5] = listAttendance.get(i).getLocation();
                rows[6] = String.format("%.0f", listAttendance.get(i).getDuration());
                rows[7] = listAttendance.get(i).getStatus();
                rows[8] = listAttendance.get(i).getInformation();

                defaultTableModel.addRow(rows);
            }
            formLeaveMainLeaveTable.setAutoCreateRowSorter(true);
            setListAttendance(listAttendance);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }

    public void searchDataAttendance() {
        try {
            Date dateFrom = formLeaveMainLeaveJDateChooseFrom.getDate();
            Date dateTo = formLeaveMainLeaveJDateChooseTo.getDate();
            SimpleDateFormat simpleDateFormatFrom = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            SimpleDateFormat simpleDateFormatTo = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            
            String keyword = formLeaveMainLeaveTextFieldFullName.getText();
            String date_from = null;
            String date_to = null;
            
            if(dateFrom != null && dateTo != null){
                date_from = simpleDateFormatFrom.format(dateFrom);
                date_to = simpleDateFormatTo.format(dateTo);
            }

            List<Attendance> listAttendance;
            if (formLeaveHeaderLabelNik.getText().equals("hrd")
                    || formLeaveHeaderLabelNik.getText().equals("admin")) {
                listAttendance = Attendance.listParams()
                        .withUsername(keyword)
                        .withDateFrom(date_from)
                        .withDateTo(date_to)
                        .build();
            } else {
                listAttendance = Attendance.listParams()
                        .withUsername(formLeaveHeaderLabelNik.getText())
                        .withDateFrom(date_from)
                        .withDateTo(date_to)
                        .build();
            }

            DefaultTableModel defaultTableModel = (DefaultTableModel) formLeaveMainLeaveTable.getModel();
            defaultTableModel.setRowCount(0);
            Object[] rows = new Object[9];
            for (int i = 0; i < listAttendance.size(); i++) {
                TableColumnModel tableColumnModel = formLeaveMainLeaveTable.getColumnModel();
                tableColumnModel.getColumn(0).setMaxWidth(0);
                tableColumnModel.getColumn(0).setMinWidth(0);

                rows[0] = listAttendance.get(i).getId();
                rows[1] = listAttendance.get(i).getUsername();
                rows[2] = listAttendance.get(i).getFullName();
                rows[3] = listAttendance.get(i).getCheckIn();
                rows[4] = listAttendance.get(i).getCheckOut();
                rows[5] = listAttendance.get(i).getLocation();
                rows[6] = String.format("%.0f", listAttendance.get(i).getDuration());
                rows[7] = listAttendance.get(i).getStatus();
                rows[8] = listAttendance.get(i).getInformation();

                defaultTableModel.addRow(rows);
            }
            formLeaveMainLeaveTable.setAutoCreateRowSorter(true);
            setListAttendance(listAttendance);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }

    private boolean generateReport() {
        boolean result = false;
        Document document = new Document();
        try {
            //font setting
            Font bfBold12 = new Font(FontFamily.TIMES_ROMAN, 12, Font.BOLD, new BaseColor(Color.BLACK));
            Font bfNormal12 = new Font(FontFamily.TIMES_ROMAN, 12);

            //document header attributes
            document.addAuthor(Constanta.PdfDocument.DOCUMENT_AUTHOR);
            document.addCreationDate();
            document.addProducer();
            document.addCreator(Constanta.PdfDocument.DOCUMENT_CREATOR);
            document.addTitle(Constanta.PdfDocument.DOCUMENT_TITLE_ATTENDANCE);
            document.setPageSize(PageSize.A4.rotate());
            
            PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(
                    Constanta.PdfDocument.PATH + "Attendance" + localDateTimeNow.format(DATETIME_PDF_FORMATTER) + ".pdf"));
            document.open();

            PdfPTable pdfPTable = new PdfPTable(8);
            pdfPTable.setWidthPercentage(Constanta.PdfDocument.WIDTH_PERCENTAGE);
            pdfPTable.setSpacingBefore(Constanta.PdfDocument.SPACING_BEFORE);
            pdfPTable.setSpacingAfter(Constanta.PdfDocument.SPACING_AFTER);

            float[] columnWidth = {3f, 3f, 2f, 2f, 2f, 2f, 2f, 5f};
            pdfPTable.setWidths(columnWidth);

            insertCell(pdfPTable, "Nik", Element.ALIGN_CENTER, 1, bfBold12);
            insertCell(pdfPTable, "Full Name", Element.ALIGN_CENTER, 1, bfBold12);
            insertCell(pdfPTable, "Check In", Element.ALIGN_CENTER, 1, bfBold12);
            insertCell(pdfPTable, "Check Out", Element.ALIGN_CENTER, 1, bfBold12);
            insertCell(pdfPTable, "Location", Element.ALIGN_CENTER, 1, bfBold12);
            insertCell(pdfPTable, "Duration", Element.ALIGN_CENTER, 1, bfBold12);
            insertCell(pdfPTable, "Status", Element.ALIGN_CENTER, 1, bfBold12);
            insertCell(pdfPTable, "Information", Element.ALIGN_CENTER, 1, bfBold12);
            pdfPTable.setHeaderRows(1);

            for (int i = 0; i < getListAttendance().size(); i++) {
                insertCell(pdfPTable, getListAttendance().get(i).getUsername(), Element.ALIGN_LEFT, 1, bfNormal12);
                insertCell(pdfPTable, getListAttendance().get(i).getFullName(), Element.ALIGN_LEFT, 1, bfNormal12);
                insertCell(pdfPTable, getListAttendance().get(i).getCheckIn(), Element.ALIGN_CENTER, 1, bfNormal12);
                insertCell(pdfPTable, getListAttendance().get(i).getCheckOut(), Element.ALIGN_CENTER, 1, bfNormal12);
                insertCell(pdfPTable, getListAttendance().get(i).getLocation(), Element.ALIGN_LEFT, 1, bfNormal12);
                insertCell(pdfPTable, String.format("%.0f", getListAttendance().get(i).getDuration()), Element.ALIGN_RIGHT, 1, bfNormal12);
                insertCell(pdfPTable, getListAttendance().get(i).getStatus(), Element.ALIGN_CENTER, 1, bfNormal12);
                insertCell(pdfPTable, getListAttendance().get(i).getInformation(), Element.ALIGN_LEFT, 1, bfNormal12);
            }

            document.add(pdfPTable);
            document.close();
            pdfWriter.close();

            result = true;
        } catch (DocumentException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
            result = false;
        }
        return result;
    }

    private void insertCell(PdfPTable table, String text, int align, int colspan, Font font) {
        PdfPCell cell;
        text = text == null ? "" : text.trim();
        cell = new PdfPCell(new Phrase(text, font));
        cell.setHorizontalAlignment(align);
        cell.setColspan(colspan);

        if (text.trim().equalsIgnoreCase("")) {
            cell.setMinimumHeight(10f);
        }
        table.addCell(cell);
    }

    private void formLeaveMainLeaveTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formLeaveMainLeaveTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formLeaveMainLeaveTableMouseClicked

    private void formLeaveMainButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formLeaveMainButtonLogoutActionPerformed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formLeaveMainButtonLogoutActionPerformed

    private void formLeaveMainButtonLogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formLeaveMainButtonLogoutKeyPressed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formLeaveMainButtonLogoutKeyPressed

    private void formLeaveMainLeaveButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formLeaveMainLeaveButtonSearchActionPerformed
        // TODO add your handling code here:
        try {
            searchDataAttendance();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formLeaveMainLeaveButtonSearchActionPerformed

    private void formLeaveMainLeaveButtonSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formLeaveMainLeaveButtonSearchKeyPressed
        // TODO add your handling code here:
        try {
            searchDataAttendance();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formLeaveMainLeaveButtonSearchKeyPressed

    private void formLeaveMainButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formLeaveMainButtonBackActionPerformed
        // TODO add your handling code here:
        try {
            Dashboard dashboard = new Dashboard();
            dashboard.show();
            dashboard.setLabelId(formLeaveHeaderLabelId.getText());
            dashboard.setLabelNik(formLeaveHeaderLabelNik.getText());
            dashboard.setFullName(getFullName());
            dashboard.setAccessMenu(getAccessMenu());
            dashboard.loadDataAttendance();
            dashboard.loadDataLeave();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formLeaveMainButtonBackActionPerformed

    private void formLeaveMainButtonBackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formLeaveMainButtonBackKeyPressed
        // TODO add your handling code here:
        try {
            Dashboard dashboard = new Dashboard();
            dashboard.show();
            dashboard.setLabelId(formLeaveHeaderLabelId.getText());
            dashboard.setLabelNik(formLeaveHeaderLabelNik.getText());
            dashboard.setFullName(getFullName());
            dashboard.setAccessMenu(getAccessMenu());
            dashboard.loadDataAttendance();
            dashboard.loadDataLeave();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formLeaveMainButtonBackKeyPressed

    private void formLeaveMainLeaveGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formLeaveMainLeaveGenerateActionPerformed
        // TODO add your handling code here:
        try {
            boolean is_print = generateReport();
            if (is_print) {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
            } else {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formLeaveMainLeaveGenerateActionPerformed

    private void formLeaveMainLeaveGenerateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formLeaveMainLeaveGenerateKeyPressed
        // TODO add your handling code here:
        try {
            boolean is_print = generateReport();
            if (is_print) {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
            } else {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formLeaveMainLeaveGenerateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeaveDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel formLeaveHeaderLabelId;
    public javax.swing.JLabel formLeaveHeaderLabelNik;
    private javax.swing.JLabel formLeaveHeaderLable;
    private javax.swing.JLabel formLeaveLabelFooter2;
    private javax.swing.JButton formLeaveMainButtonBack;
    private javax.swing.JButton formLeaveMainButtonLogout;
    private javax.swing.JLabel formLeaveMainLabelFullName;
    private javax.swing.JButton formLeaveMainLeaveButtonSearch;
    private javax.swing.JButton formLeaveMainLeaveGenerate;
    private com.toedter.calendar.JDateChooser formLeaveMainLeaveJDateChooseFrom;
    private com.toedter.calendar.JDateChooser formLeaveMainLeaveJDateChooseTo;
    private javax.swing.JLabel formLeaveMainLeaveLebelFrom;
    private javax.swing.JLabel formLeaveMainLeaveLebelFullName;
    private javax.swing.JLabel formLeaveMainLeaveLebelTo;
    private javax.swing.JPanel formLeaveMainLeavePanel;
    private javax.swing.JPanel formLeaveMainLeavePanelTable;
    private javax.swing.JTable formLeaveMainLeaveTable;
    private javax.swing.JTextField formLeaveMainLeaveTextFieldFullName;
    private javax.swing.JPanel formLeavePanelFooter;
    private javax.swing.JPanel formLeavePanelHeader;
    private javax.swing.JPanel formLeavePanelMain;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
