package form;

import javax.swing.JOptionPane;
import config.Constanta;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Attendance;
import model.Employee;
import model.Leave;
import model.Payslip;
import model.Users;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 *
 */
public final class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public MainMenu() {
        initComponents();
        formDashboardHeaderLabelId.setVisible(false);
        formDashboardHeaderLabelNik.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formDashboardPanelHeader = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        formDashboardHeaderLable = new javax.swing.JLabel();
        formMainMenuPanelMain = new javax.swing.JPanel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        formDashboardMainLabelFullName = new javax.swing.JLabel();
        formDashboardMainButtonLogout = new javax.swing.JButton();
        formDashboardMainButtonApproval = new javax.swing.JButton();
        formDashboardMainButtonDashboard = new javax.swing.JButton();
        formDashboardMainButtonEmployee = new javax.swing.JButton();
        formDashboardMainButtonPayslip = new javax.swing.JButton();
        formDashboardPanelFooter = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        formDashboardHeaderLabelId = new javax.swing.JLabel();
        formDashboardHeaderLabelNik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("frameEmployee"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formDashboardPanelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formDashboardPanelHeader.setPreferredSize(new java.awt.Dimension(1280, 100));

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkGradientFocus(400);
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(1280, 100));

        formDashboardHeaderLable.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        formDashboardHeaderLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formDashboardHeaderLable.setIcon(new javax.swing.ImageIcon("D:\\dev\\.project\\ecms\\lib\\logo.png")); // NOI18N
        formDashboardHeaderLable.setMaximumSize(new java.awt.Dimension(1280, 100));
        formDashboardHeaderLable.setMinimumSize(new java.awt.Dimension(1280, 100));
        formDashboardHeaderLable.setPreferredSize(new java.awt.Dimension(1280, 100));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formDashboardHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addComponent(formDashboardHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        formDashboardHeaderLable.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout formDashboardPanelHeaderLayout = new javax.swing.GroupLayout(formDashboardPanelHeader);
        formDashboardPanelHeader.setLayout(formDashboardPanelHeaderLayout);
        formDashboardPanelHeaderLayout.setHorizontalGroup(
            formDashboardPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        formDashboardPanelHeaderLayout.setVerticalGroup(
            formDashboardPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(formDashboardPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        formDashboardPanelHeader.getAccessibleContext().setAccessibleName("");
        formDashboardPanelHeader.getAccessibleContext().setAccessibleDescription("");

        formMainMenuPanelMain.setPreferredSize(new java.awt.Dimension(1280, 570));

        kGradientPanel4.setkEndColor(new java.awt.Color(51, 153, 255));
        kGradientPanel4.setkGradientFocus(400);
        kGradientPanel4.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel4.setPreferredSize(new java.awt.Dimension(1280, 570));

        formDashboardMainLabelFullName.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        formDashboardMainLabelFullName.setText("FullName");

        formDashboardMainButtonLogout.setBackground(new java.awt.Color(255, 255, 255));
        formDashboardMainButtonLogout.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainButtonLogout.setText("Logout");
        formDashboardMainButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainButtonLogoutActionPerformed(evt);
            }
        });
        formDashboardMainButtonLogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainButtonLogoutKeyPressed(evt);
            }
        });

        formDashboardMainButtonApproval.setBackground(new java.awt.Color(51, 153, 255));
        formDashboardMainButtonApproval.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainButtonApproval.setIcon(new javax.swing.ImageIcon("D:\\dev\\.project\\ecms\\lib\\approval.png")); // NOI18N
        formDashboardMainButtonApproval.setToolTipText("Approval");
        formDashboardMainButtonApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainButtonApprovalActionPerformed(evt);
            }
        });
        formDashboardMainButtonApproval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainButtonApprovalKeyPressed(evt);
            }
        });

        formDashboardMainButtonDashboard.setBackground(new java.awt.Color(51, 153, 255));
        formDashboardMainButtonDashboard.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainButtonDashboard.setIcon(new javax.swing.ImageIcon("D:\\dev\\.project\\ecms\\lib\\dashboard.png")); // NOI18N
        formDashboardMainButtonDashboard.setToolTipText("Dashboard");
        formDashboardMainButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainButtonDashboardActionPerformed(evt);
            }
        });
        formDashboardMainButtonDashboard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainButtonDashboardKeyPressed(evt);
            }
        });

        formDashboardMainButtonEmployee.setBackground(new java.awt.Color(51, 153, 255));
        formDashboardMainButtonEmployee.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainButtonEmployee.setIcon(new javax.swing.ImageIcon("D:\\dev\\.project\\ecms\\lib\\employee.png")); // NOI18N
        formDashboardMainButtonEmployee.setToolTipText("Employee");
        formDashboardMainButtonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainButtonEmployeeActionPerformed(evt);
            }
        });
        formDashboardMainButtonEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainButtonEmployeeKeyPressed(evt);
            }
        });

        formDashboardMainButtonPayslip.setBackground(new java.awt.Color(51, 153, 255));
        formDashboardMainButtonPayslip.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formDashboardMainButtonPayslip.setIcon(new javax.swing.ImageIcon("D:\\dev\\.project\\ecms\\lib\\payslip.png")); // NOI18N
        formDashboardMainButtonPayslip.setToolTipText("Payslip");
        formDashboardMainButtonPayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formDashboardMainButtonPayslipActionPerformed(evt);
            }
        });
        formDashboardMainButtonPayslip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formDashboardMainButtonPayslipKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formDashboardMainLabelFullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formDashboardMainButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addComponent(formDashboardMainButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formDashboardMainButtonApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel4Layout.createSequentialGroup()
                        .addComponent(formDashboardMainButtonEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formDashboardMainButtonPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(335, 335, 335))
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDashboardMainButtonLogout)
                    .addComponent(formDashboardMainLabelFullName))
                .addGap(48, 48, 48)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDashboardMainButtonApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formDashboardMainButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formDashboardMainButtonEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formDashboardMainButtonPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formMainMenuPanelMainLayout = new javax.swing.GroupLayout(formMainMenuPanelMain);
        formMainMenuPanelMain.setLayout(formMainMenuPanelMainLayout);
        formMainMenuPanelMainLayout.setHorizontalGroup(
            formMainMenuPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        formMainMenuPanelMainLayout.setVerticalGroup(
            formMainMenuPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formMainMenuPanelMainLayout.createSequentialGroup()
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(formMainMenuPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        formDashboardPanelFooter.setPreferredSize(new java.awt.Dimension(1280, 50));

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setkGradientFocus(400);
        kGradientPanel3.setkStartColor(new java.awt.Color(255, 255, 255));

        formDashboardHeaderLabelId.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formDashboardHeaderLabelId.setText("Id");
        formDashboardHeaderLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formDashboardHeaderLabelNik.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formDashboardHeaderLabelNik.setText("Nik");
        formDashboardHeaderLabelNik.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addGap(628, 628, 628)
                    .addComponent(formDashboardHeaderLabelNik)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(formDashboardHeaderLabelId)
                    .addContainerGap(628, Short.MAX_VALUE)))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formDashboardHeaderLabelNik)
                        .addComponent(formDashboardHeaderLabelId))
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout formDashboardPanelFooterLayout = new javax.swing.GroupLayout(formDashboardPanelFooter);
        formDashboardPanelFooter.setLayout(formDashboardPanelFooterLayout);
        formDashboardPanelFooterLayout.setHorizontalGroup(
            formDashboardPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        formDashboardPanelFooterLayout.setVerticalGroup(
            formDashboardPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(formDashboardPanelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, -1, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    LocalDateTime localDateTimeNow = LocalDateTime.now();
    DateTimeFormatter DATETIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private List<String> access_menu = new ArrayList<>();
    private String full_name;
    private Users users;

    public void setLabelId(String text) {
        formDashboardHeaderLabelId.setText(text);
        setMenuAccess();
    }

    public String getLabelId() {
        return formDashboardHeaderLabelId.getText();
    }

    public void setLabelNik(String text) {
        formDashboardHeaderLabelNik.setText(text);
    }

    public String getFullName() {
        return full_name;
    }

    public void setFullName(String text) {
        this.full_name = text;
        formDashboardMainLabelFullName.setText("Welcome " + text + ",");
    }

    public List<String> getAccessMenu() {
        return access_menu;
    }

    public void setAccessMenu(List<String> value) {
        this.access_menu = value;
    }
    
    public void setUsers(Users value){
        this.users = value;
    }
    
    public Users getUsers(){
        return users;
    }

    public void setMenuAccess() {
        try {
            Users users = new Users();
            users = users.get(getLabelId());
            switch (users.getIdRole()) {
                case Constanta.Role.ADMINISTRATOR:
                    formDashboardMainButtonApproval.setEnabled(false);
                    formDashboardMainButtonPayslip.setEnabled(false);
                    formDashboardMainButtonEmployee.setEnabled(true);
                    break;
                case Constanta.Role.HRD:
                    formDashboardMainButtonApproval.setEnabled(true);
                    formDashboardMainButtonPayslip.setEnabled(true);
                    formDashboardMainButtonEmployee.setEnabled(false);
                    break;
                default:
                    formDashboardMainButtonApproval.setEnabled(false);
                    formDashboardMainButtonPayslip.setEnabled(false);
                    formDashboardMainButtonEmployee.setEnabled(false);
                    break;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }

    private void formDashboardMainButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainButtonLogoutActionPerformed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonLogoutActionPerformed

    private void formDashboardMainButtonLogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainButtonLogoutKeyPressed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonLogoutKeyPressed

    private void formDashboardMainButtonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainButtonEmployeeActionPerformed
        // TODO add your handling code here:
        try {
            EmployeeManagement employeeManagement = new EmployeeManagement();
            employeeManagement.show(true);
            employeeManagement.setLabelId(formDashboardHeaderLabelId.getText());
            employeeManagement.setLabelNik(formDashboardHeaderLabelNik.getText());
            employeeManagement.setFullName(getFullName());
            employeeManagement.setAccessMenu(getAccessMenu());
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonEmployeeActionPerformed

    private void formDashboardMainButtonEmployeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainButtonEmployeeKeyPressed
        // TODO add your handling code here:
        try {
            EmployeeManagement employeeManagement = new EmployeeManagement();
            employeeManagement.show(true);
            employeeManagement.setLabelId(formDashboardHeaderLabelId.getText());
            employeeManagement.setLabelNik(formDashboardHeaderLabelNik.getText());
            employeeManagement.setFullName(getFullName());
            employeeManagement.setAccessMenu(getAccessMenu());
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonEmployeeKeyPressed

    private void formDashboardMainButtonPayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainButtonPayslipActionPerformed
        // TODO add your handling code here:
        try {
            EmployeePayslipList employeePayslipList = new EmployeePayslipList();
            employeePayslipList.show(true);
            employeePayslipList.setLabelId(formDashboardHeaderLabelId.getText());
            employeePayslipList.setLabelNik(formDashboardHeaderLabelNik.getText());
            employeePayslipList.setFullName(getFullName());
            employeePayslipList.setAccessMenu(getAccessMenu());
            employeePayslipList.loadData();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonPayslipActionPerformed

    private void formDashboardMainButtonPayslipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainButtonPayslipKeyPressed
        // TODO add your handling code here:
        try {
            EmployeePayslipList employeePayslipList = new EmployeePayslipList();
            employeePayslipList.show(true);
            employeePayslipList.setLabelId(formDashboardHeaderLabelId.getText());
            employeePayslipList.setLabelNik(formDashboardHeaderLabelNik.getText());
            employeePayslipList.setFullName(getFullName());
            employeePayslipList.setAccessMenu(getAccessMenu());
            employeePayslipList.loadData();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonPayslipKeyPressed

    private void formDashboardMainButtonApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainButtonApprovalActionPerformed
        // TODO add your handling code here:        
        try {
            ApprovalDetail approvalDetail = new ApprovalDetail();
            approvalDetail.show(true);
            approvalDetail.setLabelId(formDashboardHeaderLabelId.getText());
            approvalDetail.setLabelNik(formDashboardHeaderLabelNik.getText());
            approvalDetail.setFullName(getFullName());
            approvalDetail.setAccessMenu(getAccessMenu());
            approvalDetail.loadDataApproval();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonApprovalActionPerformed

    private void formDashboardMainButtonApprovalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainButtonApprovalKeyPressed
        // TODO add your handling code here:
        try {
            ApprovalDetail approvalDetail = new ApprovalDetail();
            approvalDetail.show(true);
            approvalDetail.setLabelId(formDashboardHeaderLabelId.getText());
            approvalDetail.setLabelNik(formDashboardHeaderLabelNik.getText());
            approvalDetail.setFullName(getFullName());
            approvalDetail.setAccessMenu(getAccessMenu());
            approvalDetail.loadDataApproval();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonApprovalKeyPressed

    private void formDashboardMainButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formDashboardMainButtonDashboardActionPerformed
        // TODO add your handling code here:
        try {
            Dashboard dashboard = new Dashboard();
            dashboard.show(true);
            dashboard.setLabelId(getUsers().getId().toString());
            dashboard.setLabelNik(getUsers().getUsername());
            dashboard.setFullName(getUsers().getFirstName().trim() + " " + getUsers().getLastName().trim());
            dashboard.setAccessMenu(getUsers().getAccessMenu());
            dashboard.loadDataAttendance();
            dashboard.loadDataLeave();
            dashboard.loadDataPayslip();
            this.dispose();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonDashboardActionPerformed

    private void formDashboardMainButtonDashboardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formDashboardMainButtonDashboardKeyPressed
        // TODO add your handling code here:
        try {
            Dashboard dashboard = new Dashboard();
            dashboard.show(true);
            dashboard.setLabelId(getUsers().getId().toString());
            dashboard.setLabelNik(getUsers().getUsername());
            dashboard.setFullName(getUsers().getFirstName().trim() + " " + getUsers().getLastName().trim());
            dashboard.setAccessMenu(getUsers().getAccessMenu());
            dashboard.loadDataAttendance();
            dashboard.loadDataLeave();
            dashboard.loadDataPayslip();
            this.dispose();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formDashboardMainButtonDashboardKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel formDashboardHeaderLabelId;
    public javax.swing.JLabel formDashboardHeaderLabelNik;
    private javax.swing.JLabel formDashboardHeaderLable;
    private javax.swing.JButton formDashboardMainButtonApproval;
    private javax.swing.JButton formDashboardMainButtonDashboard;
    private javax.swing.JButton formDashboardMainButtonEmployee;
    private javax.swing.JButton formDashboardMainButtonLogout;
    private javax.swing.JButton formDashboardMainButtonPayslip;
    private javax.swing.JLabel formDashboardMainLabelFullName;
    private javax.swing.JPanel formDashboardPanelFooter;
    private javax.swing.JPanel formDashboardPanelHeader;
    private javax.swing.JPanel formMainMenuPanelMain;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    // End of variables declaration//GEN-END:variables
}
