package form;

import javax.swing.JOptionPane;
import config.Constanta;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Calendar;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import static java.util.stream.Collectors.toMap;
import model.Employee;
import model.Payslip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 *  
 */
public class PayslipDetail extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public PayslipDetail() {
        initComponents();
        formPayslipDetailHeaderLabelId.setVisible(false);
        formPayslipDetailHeaderLabelNik.setVisible(false);
        bindYear();
        bindMonth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPayslipDetailPanelHeader = new javax.swing.JPanel();
        formPayslipDetailHeaderLable = new javax.swing.JLabel();
        formPayslipDetailHeaderLabelId = new javax.swing.JLabel();
        formPayslipDetailHeaderLabelNik = new javax.swing.JLabel();
        formPayslipDetailPanelFooter = new javax.swing.JPanel();
        formPayslipDetailLabelFooter2 = new javax.swing.JLabel();
        formPayslipDetailPanelMain = new javax.swing.JPanel();
        formPayslipDetailMainLabelFullName = new javax.swing.JLabel();
        formPayslipDetailMainButtonLogout = new javax.swing.JButton();
        formPayslipDetailMainButtonBack = new javax.swing.JButton();
        formPayslipDetailMainPayslipPanelTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        formPayslipDetailMainPayslipTable = new javax.swing.JTable();
        formPayslipDetailMainPayslipGenerate = new javax.swing.JButton();
        formPayslipDetailMainPayslipPanel = new javax.swing.JPanel();
        formPayslipDetailMainPayslipLebelFullName = new javax.swing.JLabel();
        formPayslipDetailMainPayslipLebelFrom = new javax.swing.JLabel();
        formPayslipDetailMainPayslipTextFieldFullName = new javax.swing.JTextField();
        formPayslipDetailMainPayslipButtonSearch = new javax.swing.JButton();
        formPayslipDetailMainPayslipComboBoxYear = new javax.swing.JComboBox<>();
        formPayslipDetailMainPayslipComboBoxMonth = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frameEmployee"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        formPayslipDetailPanelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formPayslipDetailPanelHeader.setPreferredSize(new java.awt.Dimension(1024, 100));

        formPayslipDetailHeaderLable.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        formPayslipDetailHeaderLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPayslipDetailHeaderLable.setText("Payslip Detail");

        formPayslipDetailHeaderLabelId.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formPayslipDetailHeaderLabelId.setText("Id");
        formPayslipDetailHeaderLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formPayslipDetailHeaderLabelNik.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formPayslipDetailHeaderLabelNik.setText("Nik");
        formPayslipDetailHeaderLabelNik.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout formPayslipDetailPanelHeaderLayout = new javax.swing.GroupLayout(formPayslipDetailPanelHeader);
        formPayslipDetailPanelHeader.setLayout(formPayslipDetailPanelHeaderLayout);
        formPayslipDetailPanelHeaderLayout.setHorizontalGroup(
            formPayslipDetailPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPayslipDetailPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPayslipDetailPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formPayslipDetailHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                    .addGroup(formPayslipDetailPanelHeaderLayout.createSequentialGroup()
                        .addComponent(formPayslipDetailHeaderLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formPayslipDetailHeaderLabelNik)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formPayslipDetailPanelHeaderLayout.setVerticalGroup(
            formPayslipDetailPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPayslipDetailPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formPayslipDetailHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPayslipDetailPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formPayslipDetailHeaderLabelId)
                    .addComponent(formPayslipDetailHeaderLabelNik)))
        );

        formPayslipDetailHeaderLable.getAccessibleContext().setAccessibleDescription("");

        formPayslipDetailPanelFooter.setPreferredSize(new java.awt.Dimension(1024, 75));

        formPayslipDetailLabelFooter2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        formPayslipDetailLabelFooter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPayslipDetailLabelFooter2.setText("Employee Content Management System CopyRight ©2021");

        javax.swing.GroupLayout formPayslipDetailPanelFooterLayout = new javax.swing.GroupLayout(formPayslipDetailPanelFooter);
        formPayslipDetailPanelFooter.setLayout(formPayslipDetailPanelFooterLayout);
        formPayslipDetailPanelFooterLayout.setHorizontalGroup(
            formPayslipDetailPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPayslipDetailPanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formPayslipDetailLabelFooter2, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                .addContainerGap())
        );
        formPayslipDetailPanelFooterLayout.setVerticalGroup(
            formPayslipDetailPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPayslipDetailPanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formPayslipDetailLabelFooter2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formPayslipDetailMainLabelFullName.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        formPayslipDetailMainLabelFullName.setText("FullName");

        formPayslipDetailMainButtonLogout.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPayslipDetailMainButtonLogout.setText("Logout");
        formPayslipDetailMainButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPayslipDetailMainButtonLogoutActionPerformed(evt);
            }
        });
        formPayslipDetailMainButtonLogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formPayslipDetailMainButtonLogoutKeyPressed(evt);
            }
        });

        formPayslipDetailMainButtonBack.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPayslipDetailMainButtonBack.setText("Back");
        formPayslipDetailMainButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPayslipDetailMainButtonBackActionPerformed(evt);
            }
        });
        formPayslipDetailMainButtonBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formPayslipDetailMainButtonBackKeyPressed(evt);
            }
        });

        formPayslipDetailMainPayslipPanelTable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payslip", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 11))); // NOI18N

        formPayslipDetailMainPayslipTable.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        formPayslipDetailMainPayslipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nik", "Full Name", "Periode", "Net Salary", "Total Working"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        formPayslipDetailMainPayslipTable.setColumnSelectionAllowed(true);
        formPayslipDetailMainPayslipTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formPayslipDetailMainPayslipTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formPayslipDetailMainPayslipTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(formPayslipDetailMainPayslipTable);
        formPayslipDetailMainPayslipTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        formPayslipDetailMainPayslipGenerate.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPayslipDetailMainPayslipGenerate.setText("Generate Payslip Report");
        formPayslipDetailMainPayslipGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPayslipDetailMainPayslipGenerateActionPerformed(evt);
            }
        });
        formPayslipDetailMainPayslipGenerate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formPayslipDetailMainPayslipGenerateKeyPressed(evt);
            }
        });

        formPayslipDetailMainPayslipLebelFullName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPayslipDetailMainPayslipLebelFullName.setText("Full Name");

        formPayslipDetailMainPayslipLebelFrom.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPayslipDetailMainPayslipLebelFrom.setText("Periode");

        formPayslipDetailMainPayslipTextFieldFullName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formPayslipDetailMainPayslipButtonSearch.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPayslipDetailMainPayslipButtonSearch.setText("Search");
        formPayslipDetailMainPayslipButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPayslipDetailMainPayslipButtonSearchActionPerformed(evt);
            }
        });
        formPayslipDetailMainPayslipButtonSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formPayslipDetailMainPayslipButtonSearchKeyPressed(evt);
            }
        });

        formPayslipDetailMainPayslipComboBoxYear.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formPayslipDetailMainPayslipComboBoxMonth.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout formPayslipDetailMainPayslipPanelLayout = new javax.swing.GroupLayout(formPayslipDetailMainPayslipPanel);
        formPayslipDetailMainPayslipPanel.setLayout(formPayslipDetailMainPayslipPanelLayout);
        formPayslipDetailMainPayslipPanelLayout.setHorizontalGroup(
            formPayslipDetailMainPayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPayslipDetailMainPayslipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formPayslipDetailMainPayslipLebelFullName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPayslipDetailMainPayslipTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formPayslipDetailMainPayslipLebelFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPayslipDetailMainPayslipComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formPayslipDetailMainPayslipComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formPayslipDetailMainPayslipButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        formPayslipDetailMainPayslipPanelLayout.setVerticalGroup(
            formPayslipDetailMainPayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPayslipDetailMainPayslipPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(formPayslipDetailMainPayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formPayslipDetailMainPayslipButtonSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formPayslipDetailMainPayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formPayslipDetailMainPayslipComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(formPayslipDetailMainPayslipComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPayslipDetailMainPayslipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formPayslipDetailMainPayslipTextFieldFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(formPayslipDetailMainPayslipLebelFullName)
                        .addComponent(formPayslipDetailMainPayslipLebelFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout formPayslipDetailMainPayslipPanelTableLayout = new javax.swing.GroupLayout(formPayslipDetailMainPayslipPanelTable);
        formPayslipDetailMainPayslipPanelTable.setLayout(formPayslipDetailMainPayslipPanelTableLayout);
        formPayslipDetailMainPayslipPanelTableLayout.setHorizontalGroup(
            formPayslipDetailMainPayslipPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPayslipDetailMainPayslipPanelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPayslipDetailMainPayslipPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formPayslipDetailMainPayslipPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formPayslipDetailMainPayslipPanelTableLayout.createSequentialGroup()
                        .addGroup(formPayslipDetailMainPayslipPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formPayslipDetailMainPayslipGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );
        formPayslipDetailMainPayslipPanelTableLayout.setVerticalGroup(
            formPayslipDetailMainPayslipPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPayslipDetailMainPayslipPanelTableLayout.createSequentialGroup()
                .addComponent(formPayslipDetailMainPayslipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formPayslipDetailMainPayslipGenerate)
                .addContainerGap())
        );

        javax.swing.GroupLayout formPayslipDetailPanelMainLayout = new javax.swing.GroupLayout(formPayslipDetailPanelMain);
        formPayslipDetailPanelMain.setLayout(formPayslipDetailPanelMainLayout);
        formPayslipDetailPanelMainLayout.setHorizontalGroup(
            formPayslipDetailPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPayslipDetailPanelMainLayout.createSequentialGroup()
                .addGroup(formPayslipDetailPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPayslipDetailPanelMainLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(formPayslipDetailMainLabelFullName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formPayslipDetailMainButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formPayslipDetailMainButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPayslipDetailPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(formPayslipDetailMainPayslipPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formPayslipDetailPanelMainLayout.setVerticalGroup(
            formPayslipDetailPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPayslipDetailPanelMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(formPayslipDetailPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formPayslipDetailMainButtonLogout)
                    .addComponent(formPayslipDetailMainLabelFullName)
                    .addComponent(formPayslipDetailMainButtonBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPayslipDetailMainPayslipPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formPayslipDetailPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(formPayslipDetailPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addComponent(formPayslipDetailPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formPayslipDetailPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPayslipDetailPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formPayslipDetailPanelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        formPayslipDetailPanelHeader.getAccessibleContext().setAccessibleName("");
        formPayslipDetailPanelHeader.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    LocalDateTime localDateTimeNow = LocalDateTime.now();
    DateTimeFormatter DATETIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    DateTimeFormatter DATETIME_PDF_FORMATTER = DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
    private List<String> access_menu = new ArrayList<>();
    private String full_name;

    public void setLabelId(String text) {
        formPayslipDetailHeaderLabelId.setText(text);
    }

    public void setLabelNik(String text) {
        formPayslipDetailHeaderLabelNik.setText(text);
    }

    public String getFullName() {
        return full_name;
    }

    public void setFullName(String text) {
        this.full_name = text;
        formPayslipDetailMainLabelFullName.setText("Welcome " + text + ",");
    }

    public List<String> getAccessMenu() {
        return access_menu;
    }

    public void setAccessMenu(List<String> value) {
        this.access_menu = value;
    }

    private List<Payslip> list_payslip;

    private void setListPayslip(List<Payslip> value) {
        this.list_payslip = value;
    }

    private List<Payslip> getListPayslip() {
        return list_payslip;
    }

    public void loadDataPayslip() {
        try {
            List<Payslip> listPayslip;
            if (formPayslipDetailHeaderLabelNik.getText().equals("hrd")
                    || formPayslipDetailHeaderLabelNik.getText().equals("admin")) {
                listPayslip = Payslip.listParams()
                        .withUsername("")
                        .withPeriode(null)
                        .build();
            } else {
                listPayslip = Payslip.listParams()
                        .withUsername(formPayslipDetailHeaderLabelNik.getText())
                        .withPeriode(null)
                        .get();
            }

            DefaultTableModel defaultTableModel = (DefaultTableModel) formPayslipDetailMainPayslipTable.getModel();
            defaultTableModel.setRowCount(0);
            Object[] rows = new Object[6];
            
            TableColumnModel tableColumnModel = formPayslipDetailMainPayslipTable.getColumnModel();
            tableColumnModel.getColumn(0).setMaxWidth(0);
            tableColumnModel.getColumn(0).setMinWidth(0);
            
            for (int i = 0; i < listPayslip.size(); i++) {
                rows[0] = listPayslip.get(i).getId();
                rows[1] = listPayslip.get(i).getUsername();
                rows[2] = listPayslip.get(i).getFullName();
                rows[3] = listPayslip.get(i).getPeriode();
                rows[4] = String.format("%.0f", listPayslip.get(i).getNetSalary());
                rows[5] = String.format("%.0f", listPayslip.get(i).getWorkingHour() + listPayslip.get(i).getOvertimeHour());

                defaultTableModel.addRow(rows);
            }
            formPayslipDetailMainPayslipTable.setAutoCreateRowSorter(true);
            setListPayslip(listPayslip);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }

    public void searchDataPayslip() {
        try {
            List<Payslip> listPayslip;
            Constanta.Default constantaDefault = new Constanta.Default();
            String periode = formPayslipDetailMainPayslipComboBoxYear.getSelectedItem() + "-" + constantaDefault.getMonth(formPayslipDetailMainPayslipComboBoxMonth.getSelectedItem().toString());
        
            if (formPayslipDetailHeaderLabelNik.getText().equals("hrd")
                    || formPayslipDetailHeaderLabelNik.getText().equals("admin")) {
                listPayslip = Payslip.listParams()
                        .withUsername(formPayslipDetailMainPayslipTextFieldFullName.getText())
                        .withPeriode(periode)
                        .build();
            } else {
                listPayslip = Payslip.listParams()
                        .withUsername(formPayslipDetailHeaderLabelNik.getText())
                        .withPeriode(periode)
                        .get();
            }

            DefaultTableModel defaultTableModel = (DefaultTableModel) formPayslipDetailMainPayslipTable.getModel();
            defaultTableModel.setRowCount(0);
            Object[] rows = new Object[6];
            
            TableColumnModel tableColumnModel = formPayslipDetailMainPayslipTable.getColumnModel();
            tableColumnModel.getColumn(0).setMaxWidth(0);
            tableColumnModel.getColumn(0).setMinWidth(0);
            
            for (int i = 0; i < listPayslip.size(); i++) {
                rows[0] = listPayslip.get(i).getId();
                rows[1] = listPayslip.get(i).getUsername();
                rows[2] = listPayslip.get(i).getFullName();
                rows[3] = listPayslip.get(i).getPeriode();
                rows[4] = String.format("%.0f", listPayslip.get(i).getNetSalary());
                rows[5] = String.format("%.0f", listPayslip.get(i).getWorkingHour() + listPayslip.get(i).getOvertimeHour());

                defaultTableModel.addRow(rows);
            }
            formPayslipDetailMainPayslipTable.setAutoCreateRowSorter(true);
            setListPayslip(listPayslip);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }
    
    private void bindYear() {
        try {
            for (int years = Calendar.getInstance().get(Calendar.YEAR); years >= 1980; years--) {
                formPayslipDetailMainPayslipComboBoxYear.addItem("" + years);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }

    private void bindMonth() {
        try {
            Constanta.Default constantaDefault = new Constanta.Default();
            HashMap<String, Integer> map = constantaDefault.getMonth();
            Map<String, Integer> sortedByValue = map.entrySet()
                    .stream()
                    .sorted(Map.Entry.<String, Integer>comparingByValue())
                    .collect(toMap(Map.Entry::getKey, Map.Entry::getValue, (e1, e2) -> e1, LinkedHashMap::new));
            sortedByValue.entrySet().forEach((entry) -> {
                formPayslipDetailMainPayslipComboBoxMonth.addItem(entry.getKey());
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }
    
    private boolean generateReport() {
        boolean result = false;
        Document document = new Document();
        try {
            //font setting
            Font bfBold12 = new Font(FontFamily.TIMES_ROMAN, 12, Font.BOLD, new BaseColor(Color.BLACK));
            Font bfNormal12 = new Font(FontFamily.TIMES_ROMAN, 12);

            //document header attributes
            document.addAuthor(Constanta.PdfDocument.DOCUMENT_AUTHOR);
            document.addCreationDate();
            document.addProducer();
            document.addCreator(Constanta.PdfDocument.DOCUMENT_CREATOR);
            document.addTitle(Constanta.PdfDocument.DOCUMENT_TITLE_ATTENDANCE);
            document.setPageSize(PageSize.A4.rotate());
            
            PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(
                    Constanta.PdfDocument.PATH + "Payslip" + localDateTimeNow.format(DATETIME_PDF_FORMATTER) + ".pdf"));
            document.open();

            PdfPTable pdfPTable = new PdfPTable(5);
            pdfPTable.setWidthPercentage(Constanta.PdfDocument.WIDTH_PERCENTAGE);
            pdfPTable.setSpacingBefore(Constanta.PdfDocument.SPACING_BEFORE);
            pdfPTable.setSpacingAfter(Constanta.PdfDocument.SPACING_AFTER);

            float[] columnWidth = {3f, 3f, 2f, 2f, 2f};
            pdfPTable.setWidths(columnWidth);
            
            insertCell(pdfPTable, "Report Payslip", Element.ALIGN_CENTER, 5, 0, bfNormal12);
            pdfPTable.setHeaderRows(1);
            insertCell(pdfPTable, "Employee Content Management System", Element.ALIGN_CENTER, 5, 0, bfNormal12);
            pdfPTable.setHeaderRows(2);
            insertCell(pdfPTable, "", Element.ALIGN_CENTER, 5, 0, bfNormal12);
            pdfPTable.setHeaderRows(3);

            insertCell(pdfPTable, "Nik", Element.ALIGN_CENTER, 1, 1, bfBold12);
            insertCell(pdfPTable, "Full Name", Element.ALIGN_CENTER, 1, 1, bfBold12);
            insertCell(pdfPTable, "Periode", Element.ALIGN_CENTER, 1, 1, bfBold12);
            insertCell(pdfPTable, "Net Salary", Element.ALIGN_CENTER, 1, 1, bfBold12);
            insertCell(pdfPTable, "Total Working", Element.ALIGN_CENTER, 1, 1, bfBold12);
            pdfPTable.setHeaderRows(4);

            for (int i = 0; i < getListPayslip().size(); i++) {
                insertCell(pdfPTable, getListPayslip().get(i).getUsername(), Element.ALIGN_LEFT, 1, 1, bfNormal12);
                insertCell(pdfPTable, getListPayslip().get(i).getFullName(), Element.ALIGN_LEFT, 1, 1, bfNormal12);
                insertCell(pdfPTable, getListPayslip().get(i).getPeriode(), Element.ALIGN_CENTER, 1, 1, bfNormal12);
                insertCell(pdfPTable, String.format("%.0f", getListPayslip().get(i).getNetSalary()), Element.ALIGN_RIGHT, 1, 1, bfNormal12);
                insertCell(pdfPTable, String.format("%.0f", getListPayslip().get(i).getWorkingHour()), Element.ALIGN_RIGHT, 1, 1, bfNormal12);
            }

            document.add(pdfPTable);
            document.close();
            pdfWriter.close();

            result = true;
        } catch (DocumentException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
            result = false;
        }
        return result;
    }

    private void insertCell(PdfPTable table, String text, int align, int colspan, int border, Font font) {
        PdfPCell cell;
        text = text == null ? "" : text.trim();
        cell = new PdfPCell(new Phrase(text, font));
        cell.setHorizontalAlignment(align);
        cell.setColspan(colspan);
        if(border == 0){
            cell.setBorder(border);
        }
        
        if (text.trim().equalsIgnoreCase("")) {
            cell.setMinimumHeight(10f);
        }
        table.addCell(cell);
    }

    private void formPayslipDetailMainPayslipTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formPayslipDetailMainPayslipTableMouseClicked
        // TODO add your handling code here:
        try {
            PrintPayslip printPayslip = new PrintPayslip();
            printPayslip.show(true);
            printPayslip.setLabelId(formPayslipDetailHeaderLabelId.getText());
            printPayslip.setLabelNik(formPayslipDetailHeaderLabelNik.getText());
            printPayslip.setFullName(getFullName());
            printPayslip.setAccessMenu(getAccessMenu());

            Employee employee = new Employee();
            int rowSelected = formPayslipDetailMainPayslipTable.getSelectedRow();
            String nik = formPayslipDetailMainPayslipTable.getValueAt(rowSelected, 1).toString();
            String periode = formPayslipDetailMainPayslipTable.getValueAt(rowSelected, 3).toString();
            employee = employee.getByNik(nik);
            printPayslip.assignValue(employee, periode);
            this.dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPayslipDetailMainPayslipTableMouseClicked

    private void formPayslipDetailMainButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPayslipDetailMainButtonLogoutActionPerformed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPayslipDetailMainButtonLogoutActionPerformed

    private void formPayslipDetailMainButtonLogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formPayslipDetailMainButtonLogoutKeyPressed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPayslipDetailMainButtonLogoutKeyPressed

    private void formPayslipDetailMainPayslipButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPayslipDetailMainPayslipButtonSearchActionPerformed
        // TODO add your handling code here:
        try {
            searchDataPayslip();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPayslipDetailMainPayslipButtonSearchActionPerformed

    private void formPayslipDetailMainPayslipButtonSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formPayslipDetailMainPayslipButtonSearchKeyPressed
        // TODO add your handling code here:
        try {
            searchDataPayslip();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPayslipDetailMainPayslipButtonSearchKeyPressed

    private void formPayslipDetailMainButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPayslipDetailMainButtonBackActionPerformed
        // TODO add your handling code here:
        try {
            Dashboard dashboard = new Dashboard();
            dashboard.show();
            dashboard.setLabelId(formPayslipDetailHeaderLabelId.getText());
            dashboard.setLabelNik(formPayslipDetailHeaderLabelNik.getText());
            dashboard.setFullName(getFullName());
            dashboard.setAccessMenu(getAccessMenu());
            dashboard.loadDataAttendance();
            dashboard.loadDataLeave();
            dashboard.loadDataPayslip();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPayslipDetailMainButtonBackActionPerformed

    private void formPayslipDetailMainButtonBackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formPayslipDetailMainButtonBackKeyPressed
        // TODO add your handling code here:
        try {
            Dashboard dashboard = new Dashboard();
            dashboard.show();
            dashboard.setLabelId(formPayslipDetailHeaderLabelId.getText());
            dashboard.setLabelNik(formPayslipDetailHeaderLabelNik.getText());
            dashboard.setFullName(getFullName());
            dashboard.setAccessMenu(getAccessMenu());
            dashboard.loadDataAttendance();
            dashboard.loadDataLeave();
            dashboard.loadDataPayslip();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPayslipDetailMainButtonBackKeyPressed

    private void formPayslipDetailMainPayslipGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPayslipDetailMainPayslipGenerateActionPerformed
        // TODO add your handling code here:
        try {
            boolean is_print = generateReport();
            if (is_print) {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
            } else {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPayslipDetailMainPayslipGenerateActionPerformed

    private void formPayslipDetailMainPayslipGenerateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formPayslipDetailMainPayslipGenerateKeyPressed
        // TODO add your handling code here:
        try {
            boolean is_print = generateReport();
            if (is_print) {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
            } else {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPayslipDetailMainPayslipGenerateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayslipDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayslipDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayslipDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayslipDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayslipDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel formPayslipDetailHeaderLabelId;
    public javax.swing.JLabel formPayslipDetailHeaderLabelNik;
    private javax.swing.JLabel formPayslipDetailHeaderLable;
    private javax.swing.JLabel formPayslipDetailLabelFooter2;
    private javax.swing.JButton formPayslipDetailMainButtonBack;
    private javax.swing.JButton formPayslipDetailMainButtonLogout;
    private javax.swing.JLabel formPayslipDetailMainLabelFullName;
    private javax.swing.JButton formPayslipDetailMainPayslipButtonSearch;
    private javax.swing.JComboBox<String> formPayslipDetailMainPayslipComboBoxMonth;
    private javax.swing.JComboBox<String> formPayslipDetailMainPayslipComboBoxYear;
    private javax.swing.JButton formPayslipDetailMainPayslipGenerate;
    private javax.swing.JLabel formPayslipDetailMainPayslipLebelFrom;
    private javax.swing.JLabel formPayslipDetailMainPayslipLebelFullName;
    private javax.swing.JPanel formPayslipDetailMainPayslipPanel;
    private javax.swing.JPanel formPayslipDetailMainPayslipPanelTable;
    private javax.swing.JTable formPayslipDetailMainPayslipTable;
    private javax.swing.JTextField formPayslipDetailMainPayslipTextFieldFullName;
    private javax.swing.JPanel formPayslipDetailPanelFooter;
    private javax.swing.JPanel formPayslipDetailPanelHeader;
    private javax.swing.JPanel formPayslipDetailPanelMain;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
