package form;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import javax.swing.JOptionPane;
import config.Constanta;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import model.Attachment;
import model.Attendance;
import model.Employee;
import model.Payslip;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 *
 */
public class PrintPayslip extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public PrintPayslip() {
        initComponents();
        formPrintPayslipHeaderLabelId.setVisible(false);
        formPrintPayslipHeaderLabelNik.setVisible(false);
        formPrintPayslipHeaderLabelNikLeave.setVisible(false);
        formPrintPayslipHeaderLabelIdLeave.setVisible(false);
        formPrintPayslipHeaderLabelNikLeave.setText(Constanta.Default.DEFAULT_VALUE);
        formPrintPayslipHeaderLabelIdLeave.setText(Constanta.Default.DEFAULT_VALUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPrintPayslipPanelHeader = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        formPrintPayslipHeaderLable = new javax.swing.JLabel();
        formPrintPayslipPanelFooter = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        formPrintPayslipHeaderLabelId = new javax.swing.JLabel();
        formPrintPayslipHeaderLabelNikLeave = new javax.swing.JLabel();
        formPrintPayslipHeaderLabelIdLeave = new javax.swing.JLabel();
        formPrintPayslipHeaderLabelNik = new javax.swing.JLabel();
        formPrintPayslipPanelMain = new javax.swing.JPanel();
        formPrintPayslipMainLabelFullNameUser = new javax.swing.JLabel();
        formPrintPayslipMainButtonBack = new javax.swing.JButton();
        formPrintPayslipMainButtonLogout = new javax.swing.JButton();
        formPrintPayslipMainPanelForm = new javax.swing.JPanel();
        formPrintPayslipMainButtonGenerate = new javax.swing.JPanel();
        formPrintPayslipMainButtonPrint = new javax.swing.JButton();
        formPrintPayslipMainLabelFullName = new javax.swing.JLabel();
        formPrintPayslipMainValueFullName = new javax.swing.JLabel();
        formPrintPayslipMainLabelNik = new javax.swing.JLabel();
        formPrintPayslipMainValueNik = new javax.swing.JLabel();
        formPrintPayslipMainLabelPeriode = new javax.swing.JLabel();
        formPrintPayslipMainValuePeriode = new javax.swing.JLabel();
        formPrintPayslipMainLabelPosition = new javax.swing.JLabel();
        formPrintPayslipMainValuePosition = new javax.swing.JLabel();
        formPrintPayslipMainLabelBasicSalary = new javax.swing.JLabel();
        formPrintPayslipMainValueBasicSalary = new javax.swing.JLabel();
        formPrintPayslipMainLabelOvertimeSalary = new javax.swing.JLabel();
        formPrintPayslipMainValueOvertimeSalary = new javax.swing.JLabel();
        formPrintPayslipMainLabelWorkingHours = new javax.swing.JLabel();
        formPrintPayslipMainValueWorkingHours = new javax.swing.JLabel();
        formPrintPayslipMainLabelPerDays = new javax.swing.JLabel();
        formPrintPayslipMainValueWorkingDays = new javax.swing.JLabel();
        formPrintPayslipMainLabelWorkingDays = new javax.swing.JLabel();
        formPrintPayslipMainLabelOvertimeHours = new javax.swing.JLabel();
        formPrintPayslipMainValueOvertimeHours = new javax.swing.JLabel();
        formPrintPayslipMainLabelBasicCuts = new javax.swing.JLabel();
        formPrintPayslipMainValueBasicCuts = new javax.swing.JLabel();
        formPrintPayslipMainLabelTaxCuts = new javax.swing.JLabel();
        formPrintPayslipMainValueTaxCuts = new javax.swing.JLabel();
        formPrintPayslipMainLabelNetSalary = new javax.swing.JLabel();
        formPrintPayslipMainValueNetSalary = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Print Payslip");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("frameEmployee"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formPrintPayslipPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        formPrintPayslipPanelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        formPrintPayslipPanelHeader.setPreferredSize(new java.awt.Dimension(1280, 70));

        kGradientPanel2.setkEndColor(new java.awt.Color(51, 153, 255));
        kGradientPanel2.setkGradientFocus(400);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(1280, 100));

        formPrintPayslipHeaderLable.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        formPrintPayslipHeaderLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPrintPayslipHeaderLable.setIcon(new javax.swing.ImageIcon("D:\\dev\\.project\\ecms\\lib\\logo.png")); // NOI18N
        formPrintPayslipHeaderLable.setMaximumSize(new java.awt.Dimension(1280, 100));
        formPrintPayslipHeaderLable.setMinimumSize(new java.awt.Dimension(1280, 100));
        formPrintPayslipHeaderLable.setPreferredSize(new java.awt.Dimension(1280, 100));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(formPrintPayslipHeaderLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(formPrintPayslipHeaderLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formPrintPayslipPanelHeaderLayout = new javax.swing.GroupLayout(formPrintPayslipPanelHeader);
        formPrintPayslipPanelHeader.setLayout(formPrintPayslipPanelHeaderLayout);
        formPrintPayslipPanelHeaderLayout.setHorizontalGroup(
            formPrintPayslipPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        formPrintPayslipPanelHeaderLayout.setVerticalGroup(
            formPrintPayslipPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPrintPayslipPanelHeaderLayout.createSequentialGroup()
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(formPrintPayslipPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));
        formPrintPayslipPanelHeader.getAccessibleContext().setAccessibleName("");
        formPrintPayslipPanelHeader.getAccessibleContext().setAccessibleDescription("");

        formPrintPayslipPanelFooter.setBackground(new java.awt.Color(255, 255, 255));
        formPrintPayslipPanelFooter.setPreferredSize(new java.awt.Dimension(1280, 50));

        kGradientPanel3.setkEndColor(new java.awt.Color(51, 153, 255));
        kGradientPanel3.setkGradientFocus(400);
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel3.setPreferredSize(new java.awt.Dimension(1280, 50));

        formPrintPayslipHeaderLabelId.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formPrintPayslipHeaderLabelId.setText("Id");
        formPrintPayslipHeaderLabelId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formPrintPayslipHeaderLabelNikLeave.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formPrintPayslipHeaderLabelNikLeave.setText("IsUpdate");
        formPrintPayslipHeaderLabelNikLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formPrintPayslipHeaderLabelIdLeave.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formPrintPayslipHeaderLabelIdLeave.setText("IdEmployee");
        formPrintPayslipHeaderLabelIdLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        formPrintPayslipHeaderLabelNik.setFont(new java.awt.Font("Roboto Light", 0, 8)); // NOI18N
        formPrintPayslipHeaderLabelNik.setText("Nik");
        formPrintPayslipHeaderLabelNik.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addGap(567, 567, 567)
                    .addComponent(formPrintPayslipHeaderLabelId)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(formPrintPayslipHeaderLabelNikLeave)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(formPrintPayslipHeaderLabelIdLeave)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(formPrintPayslipHeaderLabelNik)
                    .addContainerGap(607, Short.MAX_VALUE)))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formPrintPayslipHeaderLabelId)
                        .addComponent(formPrintPayslipHeaderLabelNikLeave)
                        .addComponent(formPrintPayslipHeaderLabelIdLeave)
                        .addComponent(formPrintPayslipHeaderLabelNik))
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout formPrintPayslipPanelFooterLayout = new javax.swing.GroupLayout(formPrintPayslipPanelFooter);
        formPrintPayslipPanelFooter.setLayout(formPrintPayslipPanelFooterLayout);
        formPrintPayslipPanelFooterLayout.setHorizontalGroup(
            formPrintPayslipPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        formPrintPayslipPanelFooterLayout.setVerticalGroup(
            formPrintPayslipPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(formPrintPayslipPanelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, -1, -1));

        formPrintPayslipPanelMain.setBackground(new java.awt.Color(255, 255, 255));
        formPrintPayslipPanelMain.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipPanelMain.setPreferredSize(new java.awt.Dimension(1280, 570));

        formPrintPayslipMainLabelFullNameUser.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        formPrintPayslipMainLabelFullNameUser.setText("FullName");

        formPrintPayslipMainButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        formPrintPayslipMainButtonBack.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainButtonBack.setText("Back");
        formPrintPayslipMainButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPrintPayslipMainButtonBackActionPerformed(evt);
            }
        });
        formPrintPayslipMainButtonBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formPrintPayslipMainButtonBackKeyPressed(evt);
            }
        });

        formPrintPayslipMainButtonLogout.setBackground(new java.awt.Color(255, 255, 255));
        formPrintPayslipMainButtonLogout.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainButtonLogout.setText("Logout");
        formPrintPayslipMainButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPrintPayslipMainButtonLogoutActionPerformed(evt);
            }
        });
        formPrintPayslipMainButtonLogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formPrintPayslipMainButtonLogoutKeyPressed(evt);
            }
        });

        formPrintPayslipMainPanelForm.setBackground(new java.awt.Color(255, 255, 255));
        formPrintPayslipMainPanelForm.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        formPrintPayslipMainButtonGenerate.setBackground(new java.awt.Color(255, 255, 255));

        formPrintPayslipMainButtonPrint.setBackground(new java.awt.Color(51, 153, 255));
        formPrintPayslipMainButtonPrint.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainButtonPrint.setText("Print");
        formPrintPayslipMainButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPrintPayslipMainButtonPrintActionPerformed(evt);
            }
        });
        formPrintPayslipMainButtonPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formPrintPayslipMainButtonPrintKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout formPrintPayslipMainButtonGenerateLayout = new javax.swing.GroupLayout(formPrintPayslipMainButtonGenerate);
        formPrintPayslipMainButtonGenerate.setLayout(formPrintPayslipMainButtonGenerateLayout);
        formPrintPayslipMainButtonGenerateLayout.setHorizontalGroup(
            formPrintPayslipMainButtonGenerateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPrintPayslipMainButtonGenerateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formPrintPayslipMainButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342))
        );
        formPrintPayslipMainButtonGenerateLayout.setVerticalGroup(
            formPrintPayslipMainButtonGenerateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPrintPayslipMainButtonGenerateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formPrintPayslipMainButtonPrint)
                .addContainerGap())
        );

        formPrintPayslipMainLabelFullName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelFullName.setText("Full Name");

        formPrintPayslipMainValueFullName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainValueFullName.setText("FullName");

        formPrintPayslipMainLabelNik.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelNik.setText("Nik");

        formPrintPayslipMainValueNik.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainValueNik.setText("Nik");

        formPrintPayslipMainLabelPeriode.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelPeriode.setText("Periode");

        formPrintPayslipMainValuePeriode.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainValuePeriode.setText("Periode");

        formPrintPayslipMainLabelPosition.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelPosition.setText("Position");

        formPrintPayslipMainValuePosition.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainValuePosition.setText("Position");

        formPrintPayslipMainLabelBasicSalary.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelBasicSalary.setText("Basic Salary");

        formPrintPayslipMainValueBasicSalary.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainValueBasicSalary.setText("BasicSalary");

        formPrintPayslipMainLabelOvertimeSalary.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelOvertimeSalary.setText("Overtime Salary");

        formPrintPayslipMainValueOvertimeSalary.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainValueOvertimeSalary.setText("OvertimeSalary");

        formPrintPayslipMainLabelWorkingHours.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelWorkingHours.setText("Working Hours");

        formPrintPayslipMainValueWorkingHours.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainValueWorkingHours.setText("WorkingHours");

        formPrintPayslipMainLabelPerDays.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelPerDays.setText("/");

        formPrintPayslipMainValueWorkingDays.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainValueWorkingDays.setText("Days");

        formPrintPayslipMainLabelWorkingDays.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelWorkingDays.setText("Days");

        formPrintPayslipMainLabelOvertimeHours.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelOvertimeHours.setText("Overtime Hours");

        formPrintPayslipMainValueOvertimeHours.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainValueOvertimeHours.setText("OvertimeHours");

        formPrintPayslipMainLabelBasicCuts.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelBasicCuts.setText("Basic Cuts");

        formPrintPayslipMainValueBasicCuts.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainValueBasicCuts.setText("BasicCuts");

        formPrintPayslipMainLabelTaxCuts.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainLabelTaxCuts.setText("Tax Cuts");

        formPrintPayslipMainValueTaxCuts.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formPrintPayslipMainValueTaxCuts.setText("Tax Cuts");

        formPrintPayslipMainLabelNetSalary.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        formPrintPayslipMainLabelNetSalary.setText("Net Salary");

        formPrintPayslipMainValueNetSalary.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        formPrintPayslipMainValueNetSalary.setText("NetSalary");

        javax.swing.GroupLayout formPrintPayslipMainPanelFormLayout = new javax.swing.GroupLayout(formPrintPayslipMainPanelForm);
        formPrintPayslipMainPanelForm.setLayout(formPrintPayslipMainPanelFormLayout);
        formPrintPayslipMainPanelFormLayout.setHorizontalGroup(
            formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formPrintPayslipMainButtonGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                        .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                                .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(formPrintPayslipMainLabelWorkingHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(formPrintPayslipMainLabelBasicSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(formPrintPayslipMainLabelFullName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(formPrintPayslipMainLabelNik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(74, 74, 74))
                            .addGroup(formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                                .addComponent(formPrintPayslipMainLabelBasicCuts, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addGap(102, 102, 102)))
                        .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(formPrintPayslipMainValueBasicCuts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formPrintPayslipMainValueNik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formPrintPayslipMainValueBasicSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formPrintPayslipMainValueFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addGroup(formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                                .addComponent(formPrintPayslipMainValueWorkingHours)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(formPrintPayslipMainLabelPerDays)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formPrintPayslipMainValueWorkingDays)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formPrintPayslipMainLabelWorkingDays)))
                        .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                                        .addGap(208, 208, 208)
                                        .addComponent(formPrintPayslipMainValueNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(formPrintPayslipMainValueTaxCuts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(formPrintPayslipMainValueOvertimeHours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(formPrintPayslipMainLabelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formPrintPayslipMainLabelPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formPrintPayslipMainLabelOvertimeSalary)
                                    .addComponent(formPrintPayslipMainLabelOvertimeHours)
                                    .addComponent(formPrintPayslipMainLabelTaxCuts)
                                    .addComponent(formPrintPayslipMainLabelNetSalary))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(formPrintPayslipMainValuePosition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formPrintPayslipMainValueOvertimeSalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formPrintPayslipMainValuePeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        formPrintPayslipMainPanelFormLayout.setVerticalGroup(
            formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                        .addComponent(formPrintPayslipMainValuePeriode)
                        .addGap(18, 18, 18)
                        .addComponent(formPrintPayslipMainValuePosition)
                        .addGap(18, 18, 18)
                        .addComponent(formPrintPayslipMainValueOvertimeSalary))
                    .addGroup(formPrintPayslipMainPanelFormLayout.createSequentialGroup()
                        .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formPrintPayslipMainValueFullName)
                            .addComponent(formPrintPayslipMainLabelPeriode)
                            .addComponent(formPrintPayslipMainLabelFullName))
                        .addGap(20, 20, 20)
                        .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formPrintPayslipMainValueNik)
                            .addComponent(formPrintPayslipMainLabelPosition)
                            .addComponent(formPrintPayslipMainLabelNik))
                        .addGap(18, 18, 18)
                        .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formPrintPayslipMainValueBasicSalary)
                            .addComponent(formPrintPayslipMainLabelOvertimeSalary)
                            .addComponent(formPrintPayslipMainLabelBasicSalary))))
                .addGap(18, 18, 18)
                .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formPrintPayslipMainLabelWorkingHours)
                    .addComponent(formPrintPayslipMainValueOvertimeHours)
                    .addComponent(formPrintPayslipMainValueWorkingHours)
                    .addComponent(formPrintPayslipMainLabelOvertimeHours)
                    .addComponent(formPrintPayslipMainLabelPerDays)
                    .addComponent(formPrintPayslipMainValueWorkingDays)
                    .addComponent(formPrintPayslipMainLabelWorkingDays))
                .addGap(18, 18, 18)
                .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formPrintPayslipMainValueTaxCuts)
                    .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(formPrintPayslipMainLabelTaxCuts)
                        .addComponent(formPrintPayslipMainValueBasicCuts)
                        .addComponent(formPrintPayslipMainLabelBasicCuts)))
                .addGap(18, 18, 18)
                .addGroup(formPrintPayslipMainPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formPrintPayslipMainValueNetSalary)
                    .addComponent(formPrintPayslipMainLabelNetSalary))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(formPrintPayslipMainButtonGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout formPrintPayslipPanelMainLayout = new javax.swing.GroupLayout(formPrintPayslipPanelMain);
        formPrintPayslipPanelMain.setLayout(formPrintPayslipPanelMainLayout);
        formPrintPayslipPanelMainLayout.setHorizontalGroup(
            formPrintPayslipPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPrintPayslipPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPrintPayslipPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPrintPayslipPanelMainLayout.createSequentialGroup()
                        .addComponent(formPrintPayslipMainLabelFullNameUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 910, Short.MAX_VALUE)
                        .addComponent(formPrintPayslipMainButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formPrintPayslipMainButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(formPrintPayslipMainPanelForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formPrintPayslipPanelMainLayout.setVerticalGroup(
            formPrintPayslipPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPrintPayslipPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPrintPayslipPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formPrintPayslipMainButtonLogout)
                    .addComponent(formPrintPayslipMainLabelFullNameUser)
                    .addComponent(formPrintPayslipMainButtonBack))
                .addGap(69, 69, 69)
                .addComponent(formPrintPayslipMainPanelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        getContentPane().add(formPrintPayslipPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    LocalDateTime localDateTimeNow = LocalDateTime.now();
    DateTimeFormatter DATETIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
    DateTimeFormatter DATETIME_PDF_FORMATTER = DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
    private List<String> access_menu = new ArrayList<>();
    private String full_name;
    public List<Attachment> list_attachments = new ArrayList<>();
    private Payslip payslip = new Payslip();

    public void setLabelId(String text) {
        formPrintPayslipHeaderLabelId.setText(text);
    }

    public void setLabelNik(String text) {
        formPrintPayslipHeaderLabelNik.setText(text);
    }

    public String getFullName() {
        return full_name;
    }

    public void setFullName(String text) {
        this.full_name = text;
        formPrintPayslipMainLabelFullNameUser.setText("Welcome " + text + ",");
    }

    public List<String> getAccessMenu() {
        return access_menu;
    }

    public void setAccessMenu(List<String> value) {
        this.access_menu = value;
    }

    public void setListAttachment(List<Attachment> value) {
        this.list_attachments = value;
    }

    public List<Attachment> getListAttachment() {
        return list_attachments;
    }

    public void setPayslip(Payslip value) {
        this.payslip = value;
    }

    public Payslip getPayslip() {
        return payslip;
    }

    @SuppressWarnings("empty-statement")
    private void generate() throws SQLException {
        Attendance attendance = new Attendance();
        DecimalFormat decimalFormat = new DecimalFormat("#.00");
        DecimalFormat integerFormat = new DecimalFormat("#");

        String periode = formPrintPayslipMainValuePeriode.getText();
        String nik = formPrintPayslipMainValueNik.getText();
        List<Attendance> listAttendance = attendance.getByUsernameAndPeriode(nik, periode);

        int totalPresent = 0;
        for (Attendance item : listAttendance) {
            totalPresent++;
        }

        List<Payslip> listPayslip = payslip.searchByUsernameAndPeriode(nik, periode);
        for (Payslip payslip : listPayslip) {
            formPrintPayslipMainValueBasicSalary.setText(decimalFormat.format(payslip.getBasicSalary()));
            formPrintPayslipMainValueOvertimeSalary.setText(decimalFormat.format(payslip.getOvertimeSalary()));
            formPrintPayslipMainValueWorkingHours.setText(integerFormat.format(payslip.getWorkingHour()));
            formPrintPayslipMainValueWorkingDays.setText(integerFormat.format(totalPresent));
            formPrintPayslipMainValueOvertimeHours.setText(integerFormat.format(payslip.getOvertimeHour()));
            formPrintPayslipMainValueBasicCuts.setText(decimalFormat.format(payslip.getBasicCuts()));
            formPrintPayslipMainValueTaxCuts.setText(decimalFormat.format(payslip.getTaxCuts()));
            formPrintPayslipMainValueNetSalary.setText(decimalFormat.format(payslip.getNetSalary()));
        }
    }

    public void assignValue(Employee employee, String periode) {
        try {
            formPrintPayslipHeaderLabelNikLeave.setText(employee.getNik());
            formPrintPayslipHeaderLabelIdLeave.setText(employee.getId().toString());
            formPrintPayslipMainValueFullName.setText(employee.getFirstName() + " " + employee.getLastName());
            formPrintPayslipMainValueNik.setText(employee.getNik());
            formPrintPayslipMainValuePosition.setText(employee.getPositionName());
            formPrintPayslipMainValuePeriode.setText(periode);
            generate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }

    private boolean generateReport() throws BadElementException, IOException {
        boolean result = false;
        Document document = new Document();
        try {
            //font setting
            Font bfBold14 = new Font(Font.FontFamily.TIMES_ROMAN, 14, Font.BOLD, new BaseColor(Color.BLACK));
            Font bfNormal14 = new Font(Font.FontFamily.TIMES_ROMAN, 14);
            Font bfNormal12 = new Font(Font.FontFamily.TIMES_ROMAN, 12);

            //document header attributes
            document.addAuthor(Constanta.PdfDocument.DOCUMENT_AUTHOR);
            document.addCreationDate();
            document.addProducer();
            document.addCreator(Constanta.PdfDocument.DOCUMENT_CREATOR);
            document.addTitle(Constanta.PdfDocument.DOCUMENT_TITLE_ATTENDANCE);
            document.setPageSize(PageSize.A4);

            PdfWriter pdfWriter = PdfWriter.getInstance(document, new FileOutputStream(
                    Constanta.PdfDocument.PATH + "PayslipDetail" + localDateTimeNow.format(DATETIME_PDF_FORMATTER) + ".pdf"));
            document.open();

            PdfPTable pdfPTable = new PdfPTable(3);
            pdfPTable.setWidthPercentage(Constanta.PdfDocument.WIDTH_PERCENTAGE);
            pdfPTable.setSpacingBefore(Constanta.PdfDocument.SPACING_BEFORE);
            pdfPTable.setSpacingAfter(Constanta.PdfDocument.SPACING_AFTER);

            float[] columnWidth = {3f, 1f, 3f};
            pdfPTable.setWidths(columnWidth);
            
            String imagePath = Constanta.PdfDocument.PATH_LOGO;
            Image image = Image.getInstance(imagePath);
            image.setAlignment(Image.MIDDLE);
            
            pdfPTable.addCell(image);
            insertCell(pdfPTable, "", Element.ALIGN_CENTER, 3, bfNormal12);
            pdfPTable.setHeaderRows(1);

            insertCell(pdfPTable, "Report Payslip Detail", Element.ALIGN_CENTER, 3, bfNormal12);
            insertCell(pdfPTable, "Employee Content Management System", Element.ALIGN_CENTER, 3, bfNormal12);
            insertCell(pdfPTable, "", Element.ALIGN_CENTER, 3, bfNormal12);
            
            insertCell(pdfPTable, "Full Name", Element.ALIGN_LEFT, 1, bfNormal14);
            insertCell(pdfPTable, ":", Element.ALIGN_CENTER, 1, bfNormal14);
            insertCell(pdfPTable, formPrintPayslipMainValueFullName.getText(), Element.ALIGN_LEFT, 1, bfNormal14);

            insertCell(pdfPTable, "Nik", Element.ALIGN_LEFT, 1, bfNormal14);
            insertCell(pdfPTable, ":", Element.ALIGN_CENTER, 1, bfNormal14);
            insertCell(pdfPTable, formPrintPayslipMainValueNik.getText(), Element.ALIGN_LEFT, 1, bfNormal14);

            insertCell(pdfPTable, "Position", Element.ALIGN_LEFT, 1, bfNormal14);
            insertCell(pdfPTable, ":", Element.ALIGN_CENTER, 1, bfNormal14);
            insertCell(pdfPTable, formPrintPayslipMainValuePosition.getText(), Element.ALIGN_LEFT, 1, bfNormal14);

            insertCell(pdfPTable, "Periode", Element.ALIGN_LEFT, 1, bfNormal14);
            insertCell(pdfPTable, ":", Element.ALIGN_CENTER, 1, bfNormal14);
            insertCell(pdfPTable, formPrintPayslipMainValuePeriode.getText(), Element.ALIGN_LEFT, 1, bfNormal14);

            insertCell(pdfPTable, "Basic Salary", Element.ALIGN_LEFT, 1, bfNormal14);
            insertCell(pdfPTable, ":", Element.ALIGN_CENTER, 1, bfNormal14);
            insertCell(pdfPTable, "IDR " + formPrintPayslipMainValueBasicSalary.getText(), Element.ALIGN_LEFT, 1, bfNormal14);

            insertCell(pdfPTable, "Overtime Salary", Element.ALIGN_LEFT, 1, bfNormal14);
            insertCell(pdfPTable, ":", Element.ALIGN_CENTER, 1, bfNormal14);
            insertCell(pdfPTable, "IDR " + formPrintPayslipMainValueOvertimeSalary.getText(), Element.ALIGN_LEFT, 1, bfNormal14);

            insertCell(pdfPTable, "Working Hours", Element.ALIGN_LEFT, 1, bfNormal14);
            insertCell(pdfPTable, ":", Element.ALIGN_CENTER, 1, bfNormal14);
            insertCell(pdfPTable, formPrintPayslipMainValueWorkingHours.getText() + " / " + formPrintPayslipMainValueWorkingDays.getText() + " Days", Element.ALIGN_LEFT, 1, bfNormal14);

            insertCell(pdfPTable, "Overtime Hours", Element.ALIGN_LEFT, 1, bfNormal14);
            insertCell(pdfPTable, ":", Element.ALIGN_CENTER, 1, bfNormal14);
            insertCell(pdfPTable, formPrintPayslipMainValueOvertimeHours.getText(), Element.ALIGN_LEFT, 1, bfNormal14);

            insertCell(pdfPTable, "Basic Cuts", Element.ALIGN_LEFT, 1, bfNormal14);
            insertCell(pdfPTable, ":", Element.ALIGN_CENTER, 1, bfNormal14);
            insertCell(pdfPTable, "IDR " + formPrintPayslipMainValueBasicCuts.getText(), Element.ALIGN_LEFT, 1, bfNormal14);

            insertCell(pdfPTable, "Tax Cuts", Element.ALIGN_LEFT, 1, bfNormal14);
            insertCell(pdfPTable, ":", Element.ALIGN_CENTER, 1, bfNormal14);
            insertCell(pdfPTable, "IDR " + formPrintPayslipMainValueTaxCuts.getText(), Element.ALIGN_LEFT, 1, bfNormal14);

            insertCell(pdfPTable, "Net Salary", Element.ALIGN_LEFT, 1, bfBold14);
            insertCell(pdfPTable, ":", Element.ALIGN_CENTER, 1, bfBold14);
            insertCell(pdfPTable, "IDR " + formPrintPayslipMainValueNetSalary.getText(), Element.ALIGN_LEFT, 1, bfBold14);

            pdfPTable.setHeaderRows(2);

            document.add(pdfPTable);
            document.close();
            pdfWriter.close();

            result = true;
        } catch (DocumentException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
            result = false;
        }
        return result;
    }

    private void insertCell(PdfPTable table, String text, int align, int colspan, Font font) {
        PdfPCell cell;
        text = text == null ? "" : text.trim();
        cell = new PdfPCell(new Phrase(text, font));
        cell.setHorizontalAlignment(align);
        cell.setColspan(colspan);
        cell.setBorder(0);

        if (text.trim().equalsIgnoreCase("")) {
            cell.setMinimumHeight(10f);
        }
        table.addCell(cell);
    }

    private void formPrintPayslipMainButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPrintPayslipMainButtonBackActionPerformed
        // TODO add your handling code here:
        try {
            PayslipDetail payslipDetail = new PayslipDetail();
            payslipDetail.show(true);
            payslipDetail.setLabelId(formPrintPayslipHeaderLabelId.getText());
            payslipDetail.setLabelNik(formPrintPayslipHeaderLabelNik.getText());
            payslipDetail.setFullName(getFullName());
            payslipDetail.setAccessMenu(getAccessMenu());
            payslipDetail.loadDataPayslip();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPrintPayslipMainButtonBackActionPerformed

    private void formPrintPayslipMainButtonBackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formPrintPayslipMainButtonBackKeyPressed
        // TODO add your handling code here:
        try {
            PayslipDetail payslipDetail = new PayslipDetail();
            payslipDetail.show(true);
            payslipDetail.setLabelId(formPrintPayslipHeaderLabelId.getText());
            payslipDetail.setLabelNik(formPrintPayslipHeaderLabelNik.getText());
            payslipDetail.setFullName(getFullName());
            payslipDetail.setAccessMenu(getAccessMenu());
            payslipDetail.loadDataPayslip();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPrintPayslipMainButtonBackKeyPressed

    private void formPrintPayslipMainButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPrintPayslipMainButtonLogoutActionPerformed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPrintPayslipMainButtonLogoutActionPerformed

    private void formPrintPayslipMainButtonLogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formPrintPayslipMainButtonLogoutKeyPressed
        // TODO add your handling code here:
        try {
            int action = JOptionPane.showConfirmDialog(null,
                    Constanta.Messages.MESSAGE_CONFIRM_LOGOUT,
                    Constanta.Messages.BANNER_CONFIRM,
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (action == JOptionPane.YES_OPTION) {
                Login login = new Login();
                login.show();
                this.dispose();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPrintPayslipMainButtonLogoutKeyPressed

    private void formPrintPayslipMainButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPrintPayslipMainButtonPrintActionPerformed
        // TODO add your handling code here:
        try {
            boolean is_print = generateReport();
            if (is_print) {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
            } else {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
            }
        } catch (HeadlessException | BadElementException | IOException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPrintPayslipMainButtonPrintActionPerformed

    private void formPrintPayslipMainButtonPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formPrintPayslipMainButtonPrintKeyPressed
        // TODO add your handling code here:
        try {
            boolean is_print = generateReport();
            if (is_print) {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_SUCCESS);
            } else {
                JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_FAILED);
            }
        } catch (HeadlessException | BadElementException | IOException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formPrintPayslipMainButtonPrintKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintPayslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel formPrintPayslipHeaderLabelId;
    public javax.swing.JLabel formPrintPayslipHeaderLabelIdLeave;
    public javax.swing.JLabel formPrintPayslipHeaderLabelNik;
    public javax.swing.JLabel formPrintPayslipHeaderLabelNikLeave;
    private javax.swing.JLabel formPrintPayslipHeaderLable;
    private javax.swing.JButton formPrintPayslipMainButtonBack;
    private javax.swing.JPanel formPrintPayslipMainButtonGenerate;
    private javax.swing.JButton formPrintPayslipMainButtonLogout;
    private javax.swing.JButton formPrintPayslipMainButtonPrint;
    private javax.swing.JLabel formPrintPayslipMainLabelBasicCuts;
    private javax.swing.JLabel formPrintPayslipMainLabelBasicSalary;
    private javax.swing.JLabel formPrintPayslipMainLabelFullName;
    private javax.swing.JLabel formPrintPayslipMainLabelFullNameUser;
    private javax.swing.JLabel formPrintPayslipMainLabelNetSalary;
    private javax.swing.JLabel formPrintPayslipMainLabelNik;
    private javax.swing.JLabel formPrintPayslipMainLabelOvertimeHours;
    private javax.swing.JLabel formPrintPayslipMainLabelOvertimeSalary;
    private javax.swing.JLabel formPrintPayslipMainLabelPerDays;
    private javax.swing.JLabel formPrintPayslipMainLabelPeriode;
    private javax.swing.JLabel formPrintPayslipMainLabelPosition;
    private javax.swing.JLabel formPrintPayslipMainLabelTaxCuts;
    private javax.swing.JLabel formPrintPayslipMainLabelWorkingDays;
    private javax.swing.JLabel formPrintPayslipMainLabelWorkingHours;
    private javax.swing.JPanel formPrintPayslipMainPanelForm;
    private javax.swing.JLabel formPrintPayslipMainValueBasicCuts;
    private javax.swing.JLabel formPrintPayslipMainValueBasicSalary;
    private javax.swing.JLabel formPrintPayslipMainValueFullName;
    private javax.swing.JLabel formPrintPayslipMainValueNetSalary;
    private javax.swing.JLabel formPrintPayslipMainValueNik;
    private javax.swing.JLabel formPrintPayslipMainValueOvertimeHours;
    private javax.swing.JLabel formPrintPayslipMainValueOvertimeSalary;
    private javax.swing.JLabel formPrintPayslipMainValuePeriode;
    private javax.swing.JLabel formPrintPayslipMainValuePosition;
    private javax.swing.JLabel formPrintPayslipMainValueTaxCuts;
    private javax.swing.JLabel formPrintPayslipMainValueWorkingDays;
    private javax.swing.JLabel formPrintPayslipMainValueWorkingHours;
    private javax.swing.JPanel formPrintPayslipPanelFooter;
    private javax.swing.JPanel formPrintPayslipPanelHeader;
    private javax.swing.JPanel formPrintPayslipPanelMain;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    // End of variables declaration//GEN-END:variables
}
