package form;

import config.Connections;
import config.Constanta;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Employee;
import model.Users;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 *  
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection connection;
    Statement statement;
    ResultSet resultSet;
    String query;

    JFrame jFrameLogin = new Login();
    
    public Register() {
        initComponents();
        Connections dbConnections = new Connections();
        dbConnections.configuration();
        connection = dbConnections.connection;
        statement = dbConnections.statement;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formRegisterPanelHeader = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        formLoginLabelHeader1 = new javax.swing.JLabel();
        formRegisterPanelFooter = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        formLoginLabelFooter = new javax.swing.JLabel();
        formLoginLabelFooter2 = new javax.swing.JLabel();
        formRegisterPanelMain = new javax.swing.JPanel();
        formRegisterMainPanelButton = new javax.swing.JPanel();
        formRegisterMainButtonRegister = new javax.swing.JButton();
        formRegisterMainButtonClear = new javax.swing.JButton();
        formRegisterMainButtonLogin = new javax.swing.JButton();
        formRegisterMainLabelPassword = new javax.swing.JLabel();
        formRegisterMainLabelUsername = new javax.swing.JLabel();
        formRegisterMainLabelLastName = new javax.swing.JLabel();
        formRegisterMainLabelFirstName = new javax.swing.JLabel();
        formRegisterMainPasswordFieldPassword = new javax.swing.JPasswordField();
        formRegisterMainTextFieldUsername = new javax.swing.JTextField();
        formRegisterMainTextFieldLastName = new javax.swing.JTextField();
        formRegisterMainTextFieldFirstName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frameRegister"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formRegisterPanelHeader.setPreferredSize(new java.awt.Dimension(1024, 100));

        kGradientPanel2.setkEndColor(new java.awt.Color(51, 153, 255));
        kGradientPanel2.setkGradientFocus(400);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 204, 204));

        formLoginLabelHeader1.setBackground(new java.awt.Color(102, 153, 255));
        formLoginLabelHeader1.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        formLoginLabelHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formLoginLabelHeader1.setIcon(new javax.swing.ImageIcon("D:\\dev\\.project\\ecms\\lib\\logo.png")); // NOI18N

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formLoginLabelHeader1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formLoginLabelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout formRegisterPanelHeaderLayout = new javax.swing.GroupLayout(formRegisterPanelHeader);
        formRegisterPanelHeader.setLayout(formRegisterPanelHeaderLayout);
        formRegisterPanelHeaderLayout.setHorizontalGroup(
            formRegisterPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        formRegisterPanelHeaderLayout.setVerticalGroup(
            formRegisterPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(formRegisterPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));
        formRegisterPanelHeader.getAccessibleContext().setAccessibleName("");
        formRegisterPanelHeader.getAccessibleContext().setAccessibleDescription("");

        formRegisterPanelFooter.setPreferredSize(new java.awt.Dimension(1024, 75));

        kGradientPanel3.setkEndColor(new java.awt.Color(51, 153, 255));
        kGradientPanel3.setkGradientFocus(400);
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 204, 204));

        formLoginLabelFooter.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        formLoginLabelFooter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formLoginLabelFooter.setText("Employee Content Management System");

        formLoginLabelFooter2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        formLoginLabelFooter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formLoginLabelFooter2.setText("CopyRight ©2021");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(formLoginLabelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formLoginLabelFooter2, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formLoginLabelFooter)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel3Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(formLoginLabelFooter2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout formRegisterPanelFooterLayout = new javax.swing.GroupLayout(formRegisterPanelFooter);
        formRegisterPanelFooter.setLayout(formRegisterPanelFooterLayout);
        formRegisterPanelFooterLayout.setHorizontalGroup(
            formRegisterPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        formRegisterPanelFooterLayout.setVerticalGroup(
            formRegisterPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(formRegisterPanelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 645, 1280, -1));

        formRegisterPanelMain.setBackground(new java.awt.Color(255, 255, 255));

        formRegisterMainPanelButton.setBackground(new java.awt.Color(255, 255, 255));

        formRegisterMainButtonRegister.setBackground(new java.awt.Color(51, 153, 255));
        formRegisterMainButtonRegister.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formRegisterMainButtonRegister.setText("Register");
        formRegisterMainButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formRegisterMainButtonRegisterActionPerformed(evt);
            }
        });
        formRegisterMainButtonRegister.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formRegisterMainButtonRegisterKeyPressed(evt);
            }
        });

        formRegisterMainButtonClear.setBackground(new java.awt.Color(51, 153, 255));
        formRegisterMainButtonClear.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formRegisterMainButtonClear.setText("Clear");
        formRegisterMainButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formRegisterMainButtonClearActionPerformed(evt);
            }
        });
        formRegisterMainButtonClear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formRegisterMainButtonClearKeyPressed(evt);
            }
        });

        formRegisterMainButtonLogin.setBackground(new java.awt.Color(255, 255, 255));
        formRegisterMainButtonLogin.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formRegisterMainButtonLogin.setText("Already have account? Login");
        formRegisterMainButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formRegisterMainButtonLoginActionPerformed(evt);
            }
        });
        formRegisterMainButtonLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formRegisterMainButtonLoginKeyPressed(evt);
            }
        });

        formRegisterMainLabelPassword.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formRegisterMainLabelPassword.setText("Password");

        formRegisterMainLabelUsername.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formRegisterMainLabelUsername.setText("Username");

        formRegisterMainLabelLastName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formRegisterMainLabelLastName.setText("Last Name");

        formRegisterMainLabelFirstName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        formRegisterMainLabelFirstName.setText("First Name");

        formRegisterMainPasswordFieldPassword.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formRegisterMainTextFieldUsername.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formRegisterMainTextFieldLastName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        formRegisterMainTextFieldFirstName.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout formRegisterMainPanelButtonLayout = new javax.swing.GroupLayout(formRegisterMainPanelButton);
        formRegisterMainPanelButton.setLayout(formRegisterMainPanelButtonLayout);
        formRegisterMainPanelButtonLayout.setHorizontalGroup(
            formRegisterMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formRegisterMainPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formRegisterMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formRegisterMainPanelButtonLayout.createSequentialGroup()
                        .addGroup(formRegisterMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formRegisterMainLabelPassword)
                            .addComponent(formRegisterMainLabelLastName)
                            .addComponent(formRegisterMainLabelFirstName)
                            .addComponent(formRegisterMainLabelUsername))
                        .addGap(18, 18, 18)
                        .addGroup(formRegisterMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formRegisterMainTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formRegisterMainPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formRegisterMainTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formRegisterMainTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(formRegisterMainButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formRegisterMainButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formRegisterMainButtonLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formRegisterMainPanelButtonLayout.setVerticalGroup(
            formRegisterMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formRegisterMainPanelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formRegisterMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formRegisterMainLabelFirstName)
                    .addComponent(formRegisterMainTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formRegisterMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formRegisterMainTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formRegisterMainLabelLastName))
                .addGap(18, 18, 18)
                .addGroup(formRegisterMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formRegisterMainLabelUsername)
                    .addComponent(formRegisterMainTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formRegisterMainPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formRegisterMainLabelPassword)
                    .addComponent(formRegisterMainPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(formRegisterMainButtonRegister)
                .addGap(18, 18, 18)
                .addComponent(formRegisterMainButtonClear)
                .addGap(18, 18, 18)
                .addComponent(formRegisterMainButtonLogin)
                .addContainerGap())
        );

        javax.swing.GroupLayout formRegisterPanelMainLayout = new javax.swing.GroupLayout(formRegisterPanelMain);
        formRegisterPanelMain.setLayout(formRegisterPanelMainLayout);
        formRegisterPanelMainLayout.setHorizontalGroup(
            formRegisterPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formRegisterPanelMainLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(formRegisterMainPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        formRegisterPanelMainLayout.setVerticalGroup(
            formRegisterPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formRegisterPanelMainLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(formRegisterMainPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(formRegisterPanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 99, 1280, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearForm() {
        formRegisterMainTextFieldFirstName.setText("");
        formRegisterMainTextFieldLastName.setText("");
        formRegisterMainTextFieldUsername.setText("");
        formRegisterMainPasswordFieldPassword.setText("");
    }
    
    int id_default = 3;

    private boolean register() throws SQLException {
        Users users = new Users();
        
        users.setIdRole(id_default);
        users.setUsername(formRegisterMainTextFieldUsername.getText());
        users.setPassword(formRegisterMainPasswordFieldPassword.getText());
        users.setFirstName(formRegisterMainTextFieldFirstName.getText());
        users.setLastName(formRegisterMainTextFieldLastName.getText());
        boolean result = users.insertData(users);
        
        return result;
    }
    
    private Employee getEmployeeByNik() throws SQLException{
        Employee employee = new Employee();
        return employee.getByNik(formRegisterMainTextFieldUsername.getText());
    }
    
    private void formRegisterMainButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formRegisterMainButtonRegisterActionPerformed
        // TODO add your handling code here:
        try {
            Employee employee = (Employee)getEmployeeByNik();
            if (employee.getId() != null){
                if (register()) {
                    JOptionPane.showMessageDialog(this, Constanta.Messages.MEESAGE_REGISTER_SUCESS);
                    jFrameLogin.show(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, Constanta.Messages.MESSAGE_FAILED);
                    clearForm();
                }
            } else {
                JOptionPane.showMessageDialog(this, Constanta.Messages.MESSAGE_INVALID_REGISTER);
                clearForm();
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formRegisterMainButtonRegisterActionPerformed

    private void formRegisterMainButtonRegisterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formRegisterMainButtonRegisterKeyPressed
        // TODO add your handling code here:
        try {
            Employee employee = (Employee)getEmployeeByNik();
            if (employee.getId() != null){
                if (register()) {
                    JOptionPane.showMessageDialog(this, Constanta.Messages.MEESAGE_REGISTER_SUCESS);
                    jFrameLogin.show(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, Constanta.Messages.MESSAGE_FAILED);
                    clearForm();
                }
            } else {
                JOptionPane.showMessageDialog(this, Constanta.Messages.MESSAGE_INVALID_REGISTER);
                clearForm();
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, Constanta.Messages.MESSAGE_ERROR + e.getMessage());
        }
    }//GEN-LAST:event_formRegisterMainButtonRegisterKeyPressed

    private void formRegisterMainButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formRegisterMainButtonClearActionPerformed
        // TODO add your handling code here:
        try {
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formRegisterMainButtonClearActionPerformed

    private void formRegisterMainButtonClearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formRegisterMainButtonClearKeyPressed
        // TODO add your handling code here:
        try {
            clearForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formRegisterMainButtonClearKeyPressed

    private void formRegisterMainButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formRegisterMainButtonLoginActionPerformed
        // TODO add your handling code here:
        try {
            jFrameLogin.show(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formRegisterMainButtonLoginActionPerformed

    private void formRegisterMainButtonLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formRegisterMainButtonLoginKeyPressed
        // TODO add your handling code here:
        try {
            jFrameLogin.show(true);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formRegisterMainButtonLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel formLoginLabelFooter;
    private javax.swing.JLabel formLoginLabelFooter2;
    private javax.swing.JLabel formLoginLabelHeader;
    private javax.swing.JLabel formLoginLabelHeader1;
    private javax.swing.JPanel formLoginPanelHeader;
    private javax.swing.JButton formRegisterMainButtonClear;
    private javax.swing.JButton formRegisterMainButtonLogin;
    private javax.swing.JButton formRegisterMainButtonRegister;
    private javax.swing.JLabel formRegisterMainLabelFirstName;
    private javax.swing.JLabel formRegisterMainLabelLastName;
    private javax.swing.JLabel formRegisterMainLabelPassword;
    private javax.swing.JLabel formRegisterMainLabelUsername;
    private javax.swing.JPanel formRegisterMainPanelButton;
    private javax.swing.JPasswordField formRegisterMainPasswordFieldPassword;
    private javax.swing.JTextField formRegisterMainTextFieldFirstName;
    private javax.swing.JTextField formRegisterMainTextFieldLastName;
    private javax.swing.JTextField formRegisterMainTextFieldUsername;
    private javax.swing.JPanel formRegisterPanelFooter;
    private javax.swing.JPanel formRegisterPanelHeader;
    private javax.swing.JPanel formRegisterPanelMain;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    // End of variables declaration//GEN-END:variables
}
